// Code generated by Fern. DO NOT EDIT.

package staticwallets

import (
	context "context"

	suwardsdkgo "github.com/crylabsorg/suward-sdk-go"
	core "github.com/crylabsorg/suward-sdk-go/core"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	option "github.com/crylabsorg/suward-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List the project's static wallets, newest first. Paginated via limit and lastId.
func (c *Client) ListStaticWallets(
	ctx context.Context,
	request *suwardsdkgo.GetV1StaticWalletsRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayListStaticWalletsResponse, error) {
	response, err := c.WithRawResponse.ListStaticWallets(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a reusable deposit address with an accepted-asset allow-list
func (c *Client) CreateStaticWallet(
	ctx context.Context,
	request *suwardsdkgo.CryptopayCreateStaticWalletRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayStaticWalletResponse, error) {
	response, err := c.WithRawResponse.CreateStaticWallet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetch a single static wallet by its id.
func (c *Client) GetStaticWallet(
	ctx context.Context,
	request *suwardsdkgo.GetV1StaticWalletsStaticWalletIDRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayStaticWalletResponse, error) {
	response, err := c.WithRawResponse.GetStaticWallet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a static wallet. Its address stops being monitored and can no longer receive new deposits; previously recorded deposits are unaffected.
func (c *Client) DeleteStaticWallet(
	ctx context.Context,
	request *suwardsdkgo.DeleteV1StaticWalletsStaticWalletIDRequest,
	opts ...option.RequestOption,
) (map[string]bool, error) {
	response, err := c.WithRawResponse.DeleteStaticWallet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update a static wallet's accepted-asset allow-list, metadata, or webhook URL. Only the fields present in the body are changed.
func (c *Client) UpdateStaticWallet(
	ctx context.Context,
	request *suwardsdkgo.CryptopayUpdateStaticWalletRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayStaticWalletResponse, error) {
	response, err := c.WithRawResponse.UpdateStaticWallet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Paginated list of the deposits received by a static wallet, newest first.
func (c *Client) ListStaticWalletDeposits(
	ctx context.Context,
	request *suwardsdkgo.GetV1StaticWalletsStaticWalletIDDepositsRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayListStaticDepositsResponse, error) {
	response, err := c.WithRawResponse.ListStaticWalletDeposits(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetch a single static-wallet deposit by its id.
func (c *Client) GetStaticWalletDeposit(
	ctx context.Context,
	request *suwardsdkgo.GetV1StaticWalletsStaticWalletIDDepositsDepositIDRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayStaticDepositResponse, error) {
	response, err := c.WithRawResponse.GetStaticWalletDeposit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Drive a synthetic deposit through its lifecycle (no on-chain activity, no balance credit). Available for test-coin assets only.
func (c *Client) SimulateStaticWalletDeposit(
	ctx context.Context,
	request *suwardsdkgo.CryptopaySimulateStaticDepositRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayStaticDepositResponse, error) {
	response, err := c.WithRawResponse.SimulateStaticWalletDeposit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
