// Code generated by Fern. DO NOT EDIT.

package client

import (
	assets "github.com/crylabsorg/suward-sdk-go/assets"
	core "github.com/crylabsorg/suward-sdk-go/core"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	option "github.com/crylabsorg/suward-sdk-go/option"
	payments "github.com/crylabsorg/suward-sdk-go/payments"
	staticwallets "github.com/crylabsorg/suward-sdk-go/staticwallets"
)

type Client struct {
	Payments      *payments.Client
	StaticWallets *staticwallets.Client
	Assets        *assets.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Payments:      payments.NewClient(options),
		StaticWallets: staticwallets.NewClient(options),
		Assets:        assets.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
