// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCryptopayAssetResponse(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &CryptopayAssetResponse{}
		var fernTestValueID *CryptopayAssetID
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBlockchainID", func(t *testing.T) {
		obj := &CryptopayAssetResponse{}
		var fernTestValueBlockchainID *int
		obj.SetBlockchainID(fernTestValueBlockchainID)
		assert.Equal(t, fernTestValueBlockchainID, obj.BlockchainID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContractAddress", func(t *testing.T) {
		obj := &CryptopayAssetResponse{}
		var fernTestValueContractAddress *string
		obj.SetContractAddress(fernTestValueContractAddress)
		assert.Equal(t, fernTestValueContractAddress, obj.ContractAddress)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDecimals", func(t *testing.T) {
		obj := &CryptopayAssetResponse{}
		var fernTestValueDecimals *int
		obj.SetDecimals(fernTestValueDecimals)
		assert.Equal(t, fernTestValueDecimals, obj.Decimals)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGroup", func(t *testing.T) {
		obj := &CryptopayAssetResponse{}
		var fernTestValueGroup *string
		obj.SetGroup(fernTestValueGroup)
		assert.Equal(t, fernTestValueGroup, obj.Group)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &CryptopayAssetResponse{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCryptopayAssetResponse(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var expected *CryptopayAssetID
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetBlockchainID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var expected *int
		obj.BlockchainID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBlockchainID(), "getter should return the property value")
	})

	t.Run("GetBlockchainID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		obj.BlockchainID = nil

		// Act & Assert
		assert.Nil(t, obj.GetBlockchainID(), "getter should return nil when property is nil")
	})

	t.Run("GetBlockchainID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBlockchainID() // Should return zero value
	})

	t.Run("GetContractAddress", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var expected *string
		obj.ContractAddress = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetContractAddress(), "getter should return the property value")
	})

	t.Run("GetContractAddress_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		obj.ContractAddress = nil

		// Act & Assert
		assert.Nil(t, obj.GetContractAddress(), "getter should return nil when property is nil")
	})

	t.Run("GetContractAddress_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetContractAddress() // Should return zero value
	})

	t.Run("GetDecimals", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var expected *int
		obj.Decimals = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDecimals(), "getter should return the property value")
	})

	t.Run("GetDecimals_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		obj.Decimals = nil

		// Act & Assert
		assert.Nil(t, obj.GetDecimals(), "getter should return nil when property is nil")
	})

	t.Run("GetDecimals_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDecimals() // Should return zero value
	})

	t.Run("GetGroup", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var expected *string
		obj.Group = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGroup(), "getter should return the property value")
	})

	t.Run("GetGroup_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		obj.Group = nil

		// Act & Assert
		assert.Nil(t, obj.GetGroup(), "getter should return nil when property is nil")
	})

	t.Run("GetGroup_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGroup() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

}

func TestSettersMarkExplicitCryptopayAssetResponse(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var fernTestValueID *CryptopayAssetID

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBlockchainID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var fernTestValueBlockchainID *int

		// Act
		obj.SetBlockchainID(fernTestValueBlockchainID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContractAddress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var fernTestValueContractAddress *string

		// Act
		obj.SetContractAddress(fernTestValueContractAddress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDecimals_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var fernTestValueDecimals *int

		// Act
		obj.SetDecimals(fernTestValueDecimals)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGroup_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var fernTestValueGroup *string

		// Act
		obj.SetGroup(fernTestValueGroup)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptopayBlockchainResponse(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueID *int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIDString", func(t *testing.T) {
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueIDString *string
		obj.SetIDString(fernTestValueIDString)
		assert.Equal(t, fernTestValueIDString, obj.IDString)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEvmChainID", func(t *testing.T) {
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueEvmChainID *int
		obj.SetEvmChainID(fernTestValueEvmChainID)
		assert.Equal(t, fernTestValueEvmChainID, obj.EvmChainID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetChainName", func(t *testing.T) {
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueChainName *string
		obj.SetChainName(fernTestValueChainName)
		assert.Equal(t, fernTestValueChainName, obj.ChainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRequiredConfirmations", func(t *testing.T) {
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueRequiredConfirmations *int
		obj.SetRequiredConfirmations(fernTestValueRequiredConfirmations)
		assert.Equal(t, fernTestValueRequiredConfirmations, obj.RequiredConfirmations)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNetworkFeeUsd", func(t *testing.T) {
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueNetworkFeeUsd *string
		obj.SetNetworkFeeUsd(fernTestValueNetworkFeeUsd)
		assert.Equal(t, fernTestValueNetworkFeeUsd, obj.NetworkFeeUsd)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCryptopayBlockchainResponse(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var expected *int
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetIDString", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var expected *string
		obj.IDString = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIDString(), "getter should return the property value")
	})

	t.Run("GetIDString_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		obj.IDString = nil

		// Act & Assert
		assert.Nil(t, obj.GetIDString(), "getter should return nil when property is nil")
	})

	t.Run("GetIDString_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIDString() // Should return zero value
	})

	t.Run("GetEvmChainID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var expected *int
		obj.EvmChainID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEvmChainID(), "getter should return the property value")
	})

	t.Run("GetEvmChainID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		obj.EvmChainID = nil

		// Act & Assert
		assert.Nil(t, obj.GetEvmChainID(), "getter should return nil when property is nil")
	})

	t.Run("GetEvmChainID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEvmChainID() // Should return zero value
	})

	t.Run("GetChainName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var expected *string
		obj.ChainName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetChainName(), "getter should return the property value")
	})

	t.Run("GetChainName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		obj.ChainName = nil

		// Act & Assert
		assert.Nil(t, obj.GetChainName(), "getter should return nil when property is nil")
	})

	t.Run("GetChainName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetChainName() // Should return zero value
	})

	t.Run("GetRequiredConfirmations", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var expected *int
		obj.RequiredConfirmations = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRequiredConfirmations(), "getter should return the property value")
	})

	t.Run("GetRequiredConfirmations_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		obj.RequiredConfirmations = nil

		// Act & Assert
		assert.Nil(t, obj.GetRequiredConfirmations(), "getter should return nil when property is nil")
	})

	t.Run("GetRequiredConfirmations_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRequiredConfirmations() // Should return zero value
	})

	t.Run("GetNetworkFeeUsd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var expected *string
		obj.NetworkFeeUsd = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNetworkFeeUsd(), "getter should return the property value")
	})

	t.Run("GetNetworkFeeUsd_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		obj.NetworkFeeUsd = nil

		// Act & Assert
		assert.Nil(t, obj.GetNetworkFeeUsd(), "getter should return nil when property is nil")
	})

	t.Run("GetNetworkFeeUsd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNetworkFeeUsd() // Should return zero value
	})

}

func TestSettersMarkExplicitCryptopayBlockchainResponse(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueID *int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIDString_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueIDString *string

		// Act
		obj.SetIDString(fernTestValueIDString)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEvmChainID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueEvmChainID *int

		// Act
		obj.SetEvmChainID(fernTestValueEvmChainID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetChainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueChainName *string

		// Act
		obj.SetChainName(fernTestValueChainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRequiredConfirmations_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueRequiredConfirmations *int

		// Act
		obj.SetRequiredConfirmations(fernTestValueRequiredConfirmations)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNetworkFeeUsd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}
		var fernTestValueNetworkFeeUsd *string

		// Act
		obj.SetNetworkFeeUsd(fernTestValueNetworkFeeUsd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetV1AssetsResponse(t *testing.T) {
	t.Run("SetItems", func(t *testing.T) {
		obj := &GetV1AssetsResponse{}
		var fernTestValueItems []*CryptopayAssetResponse
		obj.SetItems(fernTestValueItems)
		assert.Equal(t, fernTestValueItems, obj.Items)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetV1AssetsResponse(t *testing.T) {
	t.Run("GetItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetV1AssetsResponse{}
		var expected []*CryptopayAssetResponse
		obj.Items = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetItems(), "getter should return the property value")
	})

	t.Run("GetItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetV1AssetsResponse{}
		obj.Items = nil

		// Act & Assert
		assert.Nil(t, obj.GetItems(), "getter should return nil when property is nil")
	})

	t.Run("GetItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetV1AssetsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetItems() // Should return zero value
	})

}

func TestSettersMarkExplicitGetV1AssetsResponse(t *testing.T) {
	t.Run("SetItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetV1AssetsResponse{}
		var fernTestValueItems []*CryptopayAssetResponse

		// Act
		obj.SetItems(fernTestValueItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCryptopayAssetResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayAssetResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CryptopayAssetResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CryptopayAssetResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CryptopayAssetResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCryptopayBlockchainResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptopayBlockchainResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CryptopayBlockchainResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CryptopayBlockchainResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CryptopayBlockchainResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGetV1AssetsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetV1AssetsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetV1AssetsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetV1AssetsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetV1AssetsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCryptopayAssetResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CryptopayAssetResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCryptopayBlockchainResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CryptopayBlockchainResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGetV1AssetsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetV1AssetsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetV1AssetsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesCryptopayAssetResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CryptopayAssetResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayAssetResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCryptopayBlockchainResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CryptopayBlockchainResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptopayBlockchainResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGetV1AssetsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetV1AssetsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetV1AssetsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
