// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	big "math/big"
)

var (
	cryptopayAssetResponseFieldID              = big.NewInt(1 << 0)
	cryptopayAssetResponseFieldBlockchainID    = big.NewInt(1 << 1)
	cryptopayAssetResponseFieldContractAddress = big.NewInt(1 << 2)
	cryptopayAssetResponseFieldDecimals        = big.NewInt(1 << 3)
	cryptopayAssetResponseFieldGroup           = big.NewInt(1 << 4)
	cryptopayAssetResponseFieldName            = big.NewInt(1 << 5)
)

type CryptopayAssetResponse struct {
	ID *CryptopayAssetID `json:"id,omitempty" url:"id,omitempty"`
	// Internal blockchain ID (corresponds to GET /v1/blockchains[].id).
	BlockchainID *int `json:"blockchainId,omitempty" url:"blockchainId,omitempty"`
	// ERC20 contract address; null for native coins (ETH, BNB, POL, XPL).
	ContractAddress *string `json:"contractAddress,omitempty" url:"contractAddress,omitempty"`
	// Number of decimal places: smallest-unit amounts are whole tokens * 10^decimals.
	Decimals *int `json:"decimals,omitempty" url:"decimals,omitempty"`
	// Asset group, e.g. USDT, USDC, ETH.
	Group *string `json:"group,omitempty" url:"group,omitempty"`
	// Human-readable asset name.
	Name *string `json:"name,omitempty" url:"name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayAssetResponse) GetID() *CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CryptopayAssetResponse) GetBlockchainID() *int {
	if c == nil {
		return nil
	}
	return c.BlockchainID
}

func (c *CryptopayAssetResponse) GetContractAddress() *string {
	if c == nil {
		return nil
	}
	return c.ContractAddress
}

func (c *CryptopayAssetResponse) GetDecimals() *int {
	if c == nil {
		return nil
	}
	return c.Decimals
}

func (c *CryptopayAssetResponse) GetGroup() *string {
	if c == nil {
		return nil
	}
	return c.Group
}

func (c *CryptopayAssetResponse) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CryptopayAssetResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayAssetResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayAssetResponse) SetID(id *CryptopayAssetID) {
	c.ID = id
	c.require(cryptopayAssetResponseFieldID)
}

// SetBlockchainID sets the BlockchainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayAssetResponse) SetBlockchainID(blockchainID *int) {
	c.BlockchainID = blockchainID
	c.require(cryptopayAssetResponseFieldBlockchainID)
}

// SetContractAddress sets the ContractAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayAssetResponse) SetContractAddress(contractAddress *string) {
	c.ContractAddress = contractAddress
	c.require(cryptopayAssetResponseFieldContractAddress)
}

// SetDecimals sets the Decimals field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayAssetResponse) SetDecimals(decimals *int) {
	c.Decimals = decimals
	c.require(cryptopayAssetResponseFieldDecimals)
}

// SetGroup sets the Group field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayAssetResponse) SetGroup(group *string) {
	c.Group = group
	c.require(cryptopayAssetResponseFieldGroup)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayAssetResponse) SetName(name *string) {
	c.Name = name
	c.require(cryptopayAssetResponseFieldName)
}

func (c *CryptopayAssetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayAssetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayAssetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayAssetResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayAssetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayAssetResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayBlockchainResponseFieldID                    = big.NewInt(1 << 0)
	cryptopayBlockchainResponseFieldIDString              = big.NewInt(1 << 1)
	cryptopayBlockchainResponseFieldEvmChainID            = big.NewInt(1 << 2)
	cryptopayBlockchainResponseFieldChainName             = big.NewInt(1 << 3)
	cryptopayBlockchainResponseFieldRequiredConfirmations = big.NewInt(1 << 4)
	cryptopayBlockchainResponseFieldNetworkFeeUsd         = big.NewInt(1 << 5)
)

type CryptopayBlockchainResponse struct {
	// Internal blockchain ID.
	ID *int `json:"id,omitempty" url:"id,omitempty"`
	// Network id-string, e.g. ETHEREUM, ARBITRUM (the suffix of an asset id-string).
	IDString *string `json:"idString,omitempty" url:"idString,omitempty"`
	// EIP-155 chain ID; null for non-EVM chains.
	EvmChainID *int `json:"evmChainId,omitempty" url:"evmChainId,omitempty"`
	// Human-readable chain name.
	ChainName *string `json:"chainName,omitempty" url:"chainName,omitempty"`
	// Block confirmations required for a payment to reach finality.
	RequiredConfirmations *int `json:"requiredConfirmations,omitempty" url:"requiredConfirmations,omitempty"`
	// Flat network-fee estimate in USD (decimal string).
	NetworkFeeUsd *string `json:"networkFeeUsd,omitempty" url:"networkFeeUsd,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayBlockchainResponse) GetID() *int {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CryptopayBlockchainResponse) GetIDString() *string {
	if c == nil {
		return nil
	}
	return c.IDString
}

func (c *CryptopayBlockchainResponse) GetEvmChainID() *int {
	if c == nil {
		return nil
	}
	return c.EvmChainID
}

func (c *CryptopayBlockchainResponse) GetChainName() *string {
	if c == nil {
		return nil
	}
	return c.ChainName
}

func (c *CryptopayBlockchainResponse) GetRequiredConfirmations() *int {
	if c == nil {
		return nil
	}
	return c.RequiredConfirmations
}

func (c *CryptopayBlockchainResponse) GetNetworkFeeUsd() *string {
	if c == nil {
		return nil
	}
	return c.NetworkFeeUsd
}

func (c *CryptopayBlockchainResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayBlockchainResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayBlockchainResponse) SetID(id *int) {
	c.ID = id
	c.require(cryptopayBlockchainResponseFieldID)
}

// SetIDString sets the IDString field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayBlockchainResponse) SetIDString(idString *string) {
	c.IDString = idString
	c.require(cryptopayBlockchainResponseFieldIDString)
}

// SetEvmChainID sets the EvmChainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayBlockchainResponse) SetEvmChainID(evmChainID *int) {
	c.EvmChainID = evmChainID
	c.require(cryptopayBlockchainResponseFieldEvmChainID)
}

// SetChainName sets the ChainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayBlockchainResponse) SetChainName(chainName *string) {
	c.ChainName = chainName
	c.require(cryptopayBlockchainResponseFieldChainName)
}

// SetRequiredConfirmations sets the RequiredConfirmations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayBlockchainResponse) SetRequiredConfirmations(requiredConfirmations *int) {
	c.RequiredConfirmations = requiredConfirmations
	c.require(cryptopayBlockchainResponseFieldRequiredConfirmations)
}

// SetNetworkFeeUsd sets the NetworkFeeUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayBlockchainResponse) SetNetworkFeeUsd(networkFeeUsd *string) {
	c.NetworkFeeUsd = networkFeeUsd
	c.require(cryptopayBlockchainResponseFieldNetworkFeeUsd)
}

func (c *CryptopayBlockchainResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayBlockchainResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayBlockchainResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayBlockchainResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayBlockchainResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayBlockchainResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getV1AssetsResponseFieldItems = big.NewInt(1 << 0)
)

type GetV1AssetsResponse struct {
	Items []*CryptopayAssetResponse `json:"items,omitempty" url:"items,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetV1AssetsResponse) GetItems() []*CryptopayAssetResponse {
	if g == nil {
		return nil
	}
	return g.Items
}

func (g *GetV1AssetsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetV1AssetsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1AssetsResponse) SetItems(items []*CryptopayAssetResponse) {
	g.Items = items
	g.require(getV1AssetsResponseFieldItems)
}

func (g *GetV1AssetsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetV1AssetsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetV1AssetsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetV1AssetsResponse) MarshalJSON() ([]byte, error) {
	type embed GetV1AssetsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetV1AssetsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
