// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	core "github.com/crylabsorg/suward-sdk-go/core"
)

// Bad Request
type BadRequestError struct {
	*core.APIError
	Body *ControllerErrorResponse
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body *ControllerErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Internal Server Error
type InternalServerError struct {
	*core.APIError
	Body *ControllerErrorResponse
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body *ControllerErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

// Not Found
type NotFoundError struct {
	*core.APIError
	Body *ControllerErrorResponse
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *ControllerErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Unauthorized
type UnauthorizedError struct {
	*core.APIError
	Body *ControllerErrorResponse
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *ControllerErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}
