// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	big "math/big"
)

var (
	postV1PaymentsPaymentIDActivateRequestFieldPaymentID = big.NewInt(1 << 0)
)

type PostV1PaymentsPaymentIDActivateRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostV1PaymentsPaymentIDActivateRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PaymentsPaymentIDActivateRequest) SetPaymentID(paymentID string) {
	p.PaymentID = paymentID
	p.require(postV1PaymentsPaymentIDActivateRequestFieldPaymentID)
}

var (
	postV1PaymentsPaymentIDCancelRequestFieldPaymentID = big.NewInt(1 << 0)
)

type PostV1PaymentsPaymentIDCancelRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostV1PaymentsPaymentIDCancelRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PaymentsPaymentIDCancelRequest) SetPaymentID(paymentID string) {
	p.PaymentID = paymentID
	p.require(postV1PaymentsPaymentIDCancelRequestFieldPaymentID)
}

var (
	cryptopayCreatePaymentRequestFieldActivationFlowSeconds = big.NewInt(1 << 0)
	cryptopayCreatePaymentRequestFieldAmount                = big.NewInt(1 << 1)
	cryptopayCreatePaymentRequestFieldAsset                 = big.NewInt(1 << 2)
	cryptopayCreatePaymentRequestFieldNetworkFeePayer       = big.NewInt(1 << 3)
	cryptopayCreatePaymentRequestFieldServiceFeePayer       = big.NewInt(1 << 4)
	cryptopayCreatePaymentRequestFieldExternalID            = big.NewInt(1 << 5)
	cryptopayCreatePaymentRequestFieldMetadata              = big.NewInt(1 << 6)
	cryptopayCreatePaymentRequestFieldPaymentWindowSeconds  = big.NewInt(1 << 7)
	cryptopayCreatePaymentRequestFieldRedirectConfig        = big.NewInt(1 << 8)
	cryptopayCreatePaymentRequestFieldUnderpaymentTolerance = big.NewInt(1 << 9)
	cryptopayCreatePaymentRequestFieldWebhookURL            = big.NewInt(1 << 10)
)

type CryptopayCreatePaymentRequest struct {
	ActivationFlowSeconds *int `json:"activationFlowSeconds,omitempty" url:"-"`
	// Merchant base amount, integer string in the asset's smallest unit. When a fee payer is customer the customer is charged more than this (gross); when merchant (default) the fee is deducted from the merchant's proceeds.
	Amount *string           `json:"amount,omitempty" url:"-"`
	Asset  *CryptopayAssetID `json:"asset,omitempty" url:"-"`
	// Who bears the network (gas) fee. Default merchant.
	NetworkFeePayer *CryptopayFeePayer `json:"networkFeePayer,omitempty" url:"-"`
	// Who bears the platform (service) fee. Default merchant.
	ServiceFeePayer       *CryptopayFeePayer          `json:"serviceFeePayer,omitempty" url:"-"`
	ExternalID            *string                     `json:"externalId,omitempty" url:"-"`
	Metadata              map[string]any              `json:"metadata,omitempty" url:"-"`
	PaymentWindowSeconds  *int                        `json:"paymentWindowSeconds,omitempty" url:"-"`
	RedirectConfig        *CryptopayRedirectConfigDto `json:"redirectConfig,omitempty" url:"-"`
	UnderpaymentTolerance *string                     `json:"underpaymentTolerance,omitempty" url:"-"`
	WebhookURL            *string                     `json:"webhookUrl,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopayCreatePaymentRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActivationFlowSeconds sets the ActivationFlowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetActivationFlowSeconds(activationFlowSeconds *int) {
	c.ActivationFlowSeconds = activationFlowSeconds
	c.require(cryptopayCreatePaymentRequestFieldActivationFlowSeconds)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopayCreatePaymentRequestFieldAmount)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayCreatePaymentRequestFieldAsset)
}

// SetNetworkFeePayer sets the NetworkFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetNetworkFeePayer(networkFeePayer *CryptopayFeePayer) {
	c.NetworkFeePayer = networkFeePayer
	c.require(cryptopayCreatePaymentRequestFieldNetworkFeePayer)
}

// SetServiceFeePayer sets the ServiceFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetServiceFeePayer(serviceFeePayer *CryptopayFeePayer) {
	c.ServiceFeePayer = serviceFeePayer
	c.require(cryptopayCreatePaymentRequestFieldServiceFeePayer)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(cryptopayCreatePaymentRequestFieldExternalID)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(cryptopayCreatePaymentRequestFieldMetadata)
}

// SetPaymentWindowSeconds sets the PaymentWindowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetPaymentWindowSeconds(paymentWindowSeconds *int) {
	c.PaymentWindowSeconds = paymentWindowSeconds
	c.require(cryptopayCreatePaymentRequestFieldPaymentWindowSeconds)
}

// SetRedirectConfig sets the RedirectConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetRedirectConfig(redirectConfig *CryptopayRedirectConfigDto) {
	c.RedirectConfig = redirectConfig
	c.require(cryptopayCreatePaymentRequestFieldRedirectConfig)
}

// SetUnderpaymentTolerance sets the UnderpaymentTolerance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetUnderpaymentTolerance(underpaymentTolerance *string) {
	c.UnderpaymentTolerance = underpaymentTolerance
	c.require(cryptopayCreatePaymentRequestFieldUnderpaymentTolerance)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cryptopayCreatePaymentRequestFieldWebhookURL)
}

func (c *CryptopayCreatePaymentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayCreatePaymentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopayCreatePaymentRequest(body)
	return nil
}

func (c *CryptopayCreatePaymentRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopayCreatePaymentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getV1PaymentsPaymentIDRequestFieldPaymentID = big.NewInt(1 << 0)
)

type GetV1PaymentsPaymentIDRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1PaymentsPaymentIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsPaymentIDRequest) SetPaymentID(paymentID string) {
	g.PaymentID = paymentID
	g.require(getV1PaymentsPaymentIDRequestFieldPaymentID)
}

var (
	getV1PaymentsRequestFieldOrder  = big.NewInt(1 << 0)
	getV1PaymentsRequestFieldLimit  = big.NewInt(1 << 1)
	getV1PaymentsRequestFieldLastID = big.NewInt(1 << 2)
)

type GetV1PaymentsRequest struct {
	// Sort order (asc/desc)
	Order *GetV1PaymentsRequestOrder `json:"-" url:"order,omitempty"`
	// Limit (default 20, max 100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Last ID for pagination
	LastID *string `json:"-" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1PaymentsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsRequest) SetOrder(order *GetV1PaymentsRequestOrder) {
	g.Order = order
	g.require(getV1PaymentsRequestFieldOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getV1PaymentsRequestFieldLimit)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsRequest) SetLastID(lastID *string) {
	g.LastID = lastID
	g.require(getV1PaymentsRequestFieldLastID)
}

var (
	cryptopayQuotePaymentRequestFieldAsset           = big.NewInt(1 << 0)
	cryptopayQuotePaymentRequestFieldAmount          = big.NewInt(1 << 1)
	cryptopayQuotePaymentRequestFieldNetworkFeePayer = big.NewInt(1 << 2)
	cryptopayQuotePaymentRequestFieldServiceFeePayer = big.NewInt(1 << 3)
)

type CryptopayQuotePaymentRequest struct {
	// Asset identifier (see GET /v1/assets for the live list).
	Asset CryptopayAssetID `json:"asset" url:"-"`
	// Merchant base amount, integer string in the asset's smallest unit. Example: "5000000" = 5 USDT. The response returns the derived gross (what the customer pays) and netAmount (what the merchant receives).
	Amount string `json:"amount" url:"-"`
	// Who bears the network (gas) fee. Default merchant.
	NetworkFeePayer *CryptopayFeePayer `json:"networkFeePayer,omitempty" url:"-"`
	// Who bears the platform (service) fee. Default merchant.
	ServiceFeePayer *CryptopayFeePayer `json:"serviceFeePayer,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopayQuotePaymentRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetAsset(asset CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayQuotePaymentRequestFieldAsset)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetAmount(amount string) {
	c.Amount = amount
	c.require(cryptopayQuotePaymentRequestFieldAmount)
}

// SetNetworkFeePayer sets the NetworkFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetNetworkFeePayer(networkFeePayer *CryptopayFeePayer) {
	c.NetworkFeePayer = networkFeePayer
	c.require(cryptopayQuotePaymentRequestFieldNetworkFeePayer)
}

// SetServiceFeePayer sets the ServiceFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetServiceFeePayer(serviceFeePayer *CryptopayFeePayer) {
	c.ServiceFeePayer = serviceFeePayer
	c.require(cryptopayQuotePaymentRequestFieldServiceFeePayer)
}

func (c *CryptopayQuotePaymentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayQuotePaymentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopayQuotePaymentRequest(body)
	return nil
}

func (c *CryptopayQuotePaymentRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopayQuotePaymentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	cryptopaySimulatePaymentRequestFieldPaymentID = big.NewInt(1 << 0)
	cryptopaySimulatePaymentRequestFieldAmount    = big.NewInt(1 << 1)
	cryptopaySimulatePaymentRequestFieldSubStatus = big.NewInt(1 << 2)
)

type CryptopaySimulatePaymentRequest struct {
	// Payment ID
	PaymentID string                         `json:"-" url:"-"`
	Amount    *string                        `json:"amount,omitempty" url:"-"`
	SubStatus *CryptopayPaymentSubStatusEnum `json:"subStatus,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopaySimulatePaymentRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulatePaymentRequest) SetPaymentID(paymentID string) {
	c.PaymentID = paymentID
	c.require(cryptopaySimulatePaymentRequestFieldPaymentID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulatePaymentRequest) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopaySimulatePaymentRequestFieldAmount)
}

// SetSubStatus sets the SubStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulatePaymentRequest) SetSubStatus(subStatus *CryptopayPaymentSubStatusEnum) {
	c.SubStatus = subStatus
	c.require(cryptopaySimulatePaymentRequestFieldSubStatus)
}

func (c *CryptopaySimulatePaymentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopaySimulatePaymentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopaySimulatePaymentRequest(body)
	return nil
}

func (c *CryptopaySimulatePaymentRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopaySimulatePaymentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Who bears a fee: merchant = deducted from the merchant's proceeds (default); customer = added on top of the customer charge.
type CryptopayFeePayer string

const (
	CryptopayFeePayerMerchant CryptopayFeePayer = "merchant"
	CryptopayFeePayerCustomer CryptopayFeePayer = "customer"
)

func NewCryptopayFeePayerFromString(s string) (CryptopayFeePayer, error) {
	switch s {
	case "merchant":
		return CryptopayFeePayerMerchant, nil
	case "customer":
		return CryptopayFeePayerCustomer, nil
	}
	var t CryptopayFeePayer
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayFeePayer) Ptr() *CryptopayFeePayer {
	return &c
}

var (
	cryptopayListPaymentsResponseFieldHasMore = big.NewInt(1 << 0)
	cryptopayListPaymentsResponseFieldItems   = big.NewInt(1 << 1)
	cryptopayListPaymentsResponseFieldLastID  = big.NewInt(1 << 2)
)

type CryptopayListPaymentsResponse struct {
	HasMore *bool                       `json:"hasMore,omitempty" url:"hasMore,omitempty"`
	Items   []*CryptopayPaymentResponse `json:"items,omitempty" url:"items,omitempty"`
	LastID  *string                     `json:"lastId,omitempty" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayListPaymentsResponse) GetHasMore() *bool {
	if c == nil {
		return nil
	}
	return c.HasMore
}

func (c *CryptopayListPaymentsResponse) GetItems() []*CryptopayPaymentResponse {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CryptopayListPaymentsResponse) GetLastID() *string {
	if c == nil {
		return nil
	}
	return c.LastID
}

func (c *CryptopayListPaymentsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayListPaymentsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListPaymentsResponse) SetHasMore(hasMore *bool) {
	c.HasMore = hasMore
	c.require(cryptopayListPaymentsResponseFieldHasMore)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListPaymentsResponse) SetItems(items []*CryptopayPaymentResponse) {
	c.Items = items
	c.require(cryptopayListPaymentsResponseFieldItems)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListPaymentsResponse) SetLastID(lastID *string) {
	c.LastID = lastID
	c.require(cryptopayListPaymentsResponseFieldLastID)
}

func (c *CryptopayListPaymentsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayListPaymentsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayListPaymentsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayListPaymentsResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayListPaymentsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayListPaymentsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayPaymentResponseFieldAcceptedAt            = big.NewInt(1 << 0)
	cryptopayPaymentResponseFieldActivatedAt           = big.NewInt(1 << 1)
	cryptopayPaymentResponseFieldActivationFlowSeconds = big.NewInt(1 << 2)
	cryptopayPaymentResponseFieldAddress               = big.NewInt(1 << 3)
	cryptopayPaymentResponseFieldAmount                = big.NewInt(1 << 4)
	cryptopayPaymentResponseFieldAmountConfirmed       = big.NewInt(1 << 5)
	cryptopayPaymentResponseFieldAmountReceived        = big.NewInt(1 << 6)
	cryptopayPaymentResponseFieldAsset                 = big.NewInt(1 << 7)
	cryptopayPaymentResponseFieldCreatedAt             = big.NewInt(1 << 8)
	cryptopayPaymentResponseFieldExpiresAt             = big.NewInt(1 << 9)
	cryptopayPaymentResponseFieldExternalID            = big.NewInt(1 << 10)
	cryptopayPaymentResponseFieldFee                   = big.NewInt(1 << 11)
	cryptopayPaymentResponseFieldID                    = big.NewInt(1 << 12)
	cryptopayPaymentResponseFieldMetadata              = big.NewInt(1 << 13)
	cryptopayPaymentResponseFieldNetworkFee            = big.NewInt(1 << 14)
	cryptopayPaymentResponseFieldQuotedPrice           = big.NewInt(1 << 15)
	cryptopayPaymentResponseFieldNetworkFeePayer       = big.NewInt(1 << 16)
	cryptopayPaymentResponseFieldServiceFeePayer       = big.NewInt(1 << 17)
	cryptopayPaymentResponseFieldPaymentWindowSeconds  = big.NewInt(1 << 18)
	cryptopayPaymentResponseFieldProjectID             = big.NewInt(1 << 19)
	cryptopayPaymentResponseFieldRedirectConfig        = big.NewInt(1 << 20)
	cryptopayPaymentResponseFieldStatus                = big.NewInt(1 << 21)
	cryptopayPaymentResponseFieldSubStatus             = big.NewInt(1 << 22)
	cryptopayPaymentResponseFieldTransactions          = big.NewInt(1 << 23)
	cryptopayPaymentResponseFieldUnderpaymentTolerance = big.NewInt(1 << 24)
	cryptopayPaymentResponseFieldUpdatedAt             = big.NewInt(1 << 25)
	cryptopayPaymentResponseFieldWebhookURL            = big.NewInt(1 << 26)
	cryptopayPaymentResponseFieldPaymentPageURL        = big.NewInt(1 << 27)
)

type CryptopayPaymentResponse struct {
	AcceptedAt            *int    `json:"acceptedAt,omitempty" url:"acceptedAt,omitempty"`
	ActivatedAt           *int    `json:"activatedAt,omitempty" url:"activatedAt,omitempty"`
	ActivationFlowSeconds *int    `json:"activationFlowSeconds,omitempty" url:"activationFlowSeconds,omitempty"`
	Address               *string `json:"address,omitempty" url:"address,omitempty"`
	// Integer string in the asset's smallest unit.
	Amount *string `json:"amount,omitempty" url:"amount,omitempty"`
	// Integer string in the asset's smallest unit.
	AmountConfirmed *string `json:"amountConfirmed,omitempty" url:"amountConfirmed,omitempty"`
	// Integer string in the asset's smallest unit.
	AmountReceived *string           `json:"amountReceived,omitempty" url:"amountReceived,omitempty"`
	Asset          *CryptopayAssetID `json:"asset,omitempty" url:"asset,omitempty"`
	CreatedAt      *int              `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	ExpiresAt      *int              `json:"expiresAt,omitempty" url:"expiresAt,omitempty"`
	ExternalID     *string           `json:"externalId,omitempty" url:"externalId,omitempty"`
	// Platform fee: 0.4% of the amount, minimum $1 equivalent. Integer string in the asset's smallest unit.
	Fee      *string        `json:"fee,omitempty" url:"fee,omitempty"`
	ID       *string        `json:"id,omitempty" url:"id,omitempty"`
	Metadata map[string]any `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Estimated on-chain (gas) cost, deducted from the received amount. Integer string in the asset's smallest unit.
	NetworkFee *string `json:"networkFee,omitempty" url:"networkFee,omitempty"`
	// USD price of the asset locked at creation, decimal string. Fees are computed from this price at settlement, so the merchant's net is deterministic.
	QuotedPrice *string `json:"quotedPrice,omitempty" url:"quotedPrice,omitempty"`
	// Who bears the network (gas) fee, echoed from creation.
	NetworkFeePayer *CryptopayFeePayer `json:"networkFeePayer,omitempty" url:"networkFeePayer,omitempty"`
	// Who bears the platform (service) fee, echoed from creation.
	ServiceFeePayer      *CryptopayFeePayer              `json:"serviceFeePayer,omitempty" url:"serviceFeePayer,omitempty"`
	PaymentWindowSeconds *int                            `json:"paymentWindowSeconds,omitempty" url:"paymentWindowSeconds,omitempty"`
	ProjectID            *string                         `json:"projectId,omitempty" url:"projectId,omitempty"`
	RedirectConfig       *CryptopayRedirectConfigDto     `json:"redirectConfig,omitempty" url:"redirectConfig,omitempty"`
	Status               *CryptopayPaymentStatusEnum     `json:"status,omitempty" url:"status,omitempty"`
	SubStatus            *CryptopayPaymentSubStatusEnum  `json:"subStatus,omitempty" url:"subStatus,omitempty"`
	Transactions         []*CryptopayTransactionResponse `json:"transactions,omitempty" url:"transactions,omitempty"`
	// Integer string in the asset's smallest unit.
	UnderpaymentTolerance *string `json:"underpaymentTolerance,omitempty" url:"underpaymentTolerance,omitempty"`
	UpdatedAt             *int    `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`
	WebhookURL            *string `json:"webhookUrl,omitempty" url:"webhookUrl,omitempty"`
	// Absolute URL of the Suward-hosted checkout page where the customer pays this payment.
	PaymentPageURL *string `json:"paymentPageUrl,omitempty" url:"paymentPageUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayPaymentResponse) GetAcceptedAt() *int {
	if c == nil {
		return nil
	}
	return c.AcceptedAt
}

func (c *CryptopayPaymentResponse) GetActivatedAt() *int {
	if c == nil {
		return nil
	}
	return c.ActivatedAt
}

func (c *CryptopayPaymentResponse) GetActivationFlowSeconds() *int {
	if c == nil {
		return nil
	}
	return c.ActivationFlowSeconds
}

func (c *CryptopayPaymentResponse) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CryptopayPaymentResponse) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CryptopayPaymentResponse) GetAmountConfirmed() *string {
	if c == nil {
		return nil
	}
	return c.AmountConfirmed
}

func (c *CryptopayPaymentResponse) GetAmountReceived() *string {
	if c == nil {
		return nil
	}
	return c.AmountReceived
}

func (c *CryptopayPaymentResponse) GetAsset() *CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.Asset
}

func (c *CryptopayPaymentResponse) GetCreatedAt() *int {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CryptopayPaymentResponse) GetExpiresAt() *int {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CryptopayPaymentResponse) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CryptopayPaymentResponse) GetFee() *string {
	if c == nil {
		return nil
	}
	return c.Fee
}

func (c *CryptopayPaymentResponse) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CryptopayPaymentResponse) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CryptopayPaymentResponse) GetNetworkFee() *string {
	if c == nil {
		return nil
	}
	return c.NetworkFee
}

func (c *CryptopayPaymentResponse) GetQuotedPrice() *string {
	if c == nil {
		return nil
	}
	return c.QuotedPrice
}

func (c *CryptopayPaymentResponse) GetNetworkFeePayer() *CryptopayFeePayer {
	if c == nil {
		return nil
	}
	return c.NetworkFeePayer
}

func (c *CryptopayPaymentResponse) GetServiceFeePayer() *CryptopayFeePayer {
	if c == nil {
		return nil
	}
	return c.ServiceFeePayer
}

func (c *CryptopayPaymentResponse) GetPaymentWindowSeconds() *int {
	if c == nil {
		return nil
	}
	return c.PaymentWindowSeconds
}

func (c *CryptopayPaymentResponse) GetProjectID() *string {
	if c == nil {
		return nil
	}
	return c.ProjectID
}

func (c *CryptopayPaymentResponse) GetRedirectConfig() *CryptopayRedirectConfigDto {
	if c == nil {
		return nil
	}
	return c.RedirectConfig
}

func (c *CryptopayPaymentResponse) GetStatus() *CryptopayPaymentStatusEnum {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CryptopayPaymentResponse) GetSubStatus() *CryptopayPaymentSubStatusEnum {
	if c == nil {
		return nil
	}
	return c.SubStatus
}

func (c *CryptopayPaymentResponse) GetTransactions() []*CryptopayTransactionResponse {
	if c == nil {
		return nil
	}
	return c.Transactions
}

func (c *CryptopayPaymentResponse) GetUnderpaymentTolerance() *string {
	if c == nil {
		return nil
	}
	return c.UnderpaymentTolerance
}

func (c *CryptopayPaymentResponse) GetUpdatedAt() *int {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CryptopayPaymentResponse) GetWebhookURL() *string {
	if c == nil {
		return nil
	}
	return c.WebhookURL
}

func (c *CryptopayPaymentResponse) GetPaymentPageURL() *string {
	if c == nil {
		return nil
	}
	return c.PaymentPageURL
}

func (c *CryptopayPaymentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayPaymentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAcceptedAt sets the AcceptedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAcceptedAt(acceptedAt *int) {
	c.AcceptedAt = acceptedAt
	c.require(cryptopayPaymentResponseFieldAcceptedAt)
}

// SetActivatedAt sets the ActivatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetActivatedAt(activatedAt *int) {
	c.ActivatedAt = activatedAt
	c.require(cryptopayPaymentResponseFieldActivatedAt)
}

// SetActivationFlowSeconds sets the ActivationFlowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetActivationFlowSeconds(activationFlowSeconds *int) {
	c.ActivationFlowSeconds = activationFlowSeconds
	c.require(cryptopayPaymentResponseFieldActivationFlowSeconds)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAddress(address *string) {
	c.Address = address
	c.require(cryptopayPaymentResponseFieldAddress)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopayPaymentResponseFieldAmount)
}

// SetAmountConfirmed sets the AmountConfirmed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAmountConfirmed(amountConfirmed *string) {
	c.AmountConfirmed = amountConfirmed
	c.require(cryptopayPaymentResponseFieldAmountConfirmed)
}

// SetAmountReceived sets the AmountReceived field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAmountReceived(amountReceived *string) {
	c.AmountReceived = amountReceived
	c.require(cryptopayPaymentResponseFieldAmountReceived)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayPaymentResponseFieldAsset)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetCreatedAt(createdAt *int) {
	c.CreatedAt = createdAt
	c.require(cryptopayPaymentResponseFieldCreatedAt)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetExpiresAt(expiresAt *int) {
	c.ExpiresAt = expiresAt
	c.require(cryptopayPaymentResponseFieldExpiresAt)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(cryptopayPaymentResponseFieldExternalID)
}

// SetFee sets the Fee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetFee(fee *string) {
	c.Fee = fee
	c.require(cryptopayPaymentResponseFieldFee)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetID(id *string) {
	c.ID = id
	c.require(cryptopayPaymentResponseFieldID)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(cryptopayPaymentResponseFieldMetadata)
}

// SetNetworkFee sets the NetworkFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetNetworkFee(networkFee *string) {
	c.NetworkFee = networkFee
	c.require(cryptopayPaymentResponseFieldNetworkFee)
}

// SetQuotedPrice sets the QuotedPrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetQuotedPrice(quotedPrice *string) {
	c.QuotedPrice = quotedPrice
	c.require(cryptopayPaymentResponseFieldQuotedPrice)
}

// SetNetworkFeePayer sets the NetworkFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetNetworkFeePayer(networkFeePayer *CryptopayFeePayer) {
	c.NetworkFeePayer = networkFeePayer
	c.require(cryptopayPaymentResponseFieldNetworkFeePayer)
}

// SetServiceFeePayer sets the ServiceFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetServiceFeePayer(serviceFeePayer *CryptopayFeePayer) {
	c.ServiceFeePayer = serviceFeePayer
	c.require(cryptopayPaymentResponseFieldServiceFeePayer)
}

// SetPaymentWindowSeconds sets the PaymentWindowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetPaymentWindowSeconds(paymentWindowSeconds *int) {
	c.PaymentWindowSeconds = paymentWindowSeconds
	c.require(cryptopayPaymentResponseFieldPaymentWindowSeconds)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetProjectID(projectID *string) {
	c.ProjectID = projectID
	c.require(cryptopayPaymentResponseFieldProjectID)
}

// SetRedirectConfig sets the RedirectConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetRedirectConfig(redirectConfig *CryptopayRedirectConfigDto) {
	c.RedirectConfig = redirectConfig
	c.require(cryptopayPaymentResponseFieldRedirectConfig)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetStatus(status *CryptopayPaymentStatusEnum) {
	c.Status = status
	c.require(cryptopayPaymentResponseFieldStatus)
}

// SetSubStatus sets the SubStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetSubStatus(subStatus *CryptopayPaymentSubStatusEnum) {
	c.SubStatus = subStatus
	c.require(cryptopayPaymentResponseFieldSubStatus)
}

// SetTransactions sets the Transactions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetTransactions(transactions []*CryptopayTransactionResponse) {
	c.Transactions = transactions
	c.require(cryptopayPaymentResponseFieldTransactions)
}

// SetUnderpaymentTolerance sets the UnderpaymentTolerance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetUnderpaymentTolerance(underpaymentTolerance *string) {
	c.UnderpaymentTolerance = underpaymentTolerance
	c.require(cryptopayPaymentResponseFieldUnderpaymentTolerance)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetUpdatedAt(updatedAt *int) {
	c.UpdatedAt = updatedAt
	c.require(cryptopayPaymentResponseFieldUpdatedAt)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cryptopayPaymentResponseFieldWebhookURL)
}

// SetPaymentPageURL sets the PaymentPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetPaymentPageURL(paymentPageURL *string) {
	c.PaymentPageURL = paymentPageURL
	c.require(cryptopayPaymentResponseFieldPaymentPageURL)
}

func (c *CryptopayPaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayPaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayPaymentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayPaymentResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayPaymentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayPaymentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Terminal states: success (finalized), failed (terminal, no valid payment). Non-final: pending (awaiting funds), accepted (safe confirmations reached, credited — non-final until finalized).
type CryptopayPaymentStatusEnum string

const (
	CryptopayPaymentStatusEnumPending  CryptopayPaymentStatusEnum = "pending"
	CryptopayPaymentStatusEnumAccepted CryptopayPaymentStatusEnum = "accepted"
	CryptopayPaymentStatusEnumSuccess  CryptopayPaymentStatusEnum = "success"
	CryptopayPaymentStatusEnumFailed   CryptopayPaymentStatusEnum = "failed"
)

func NewCryptopayPaymentStatusEnumFromString(s string) (CryptopayPaymentStatusEnum, error) {
	switch s {
	case "pending":
		return CryptopayPaymentStatusEnumPending, nil
	case "accepted":
		return CryptopayPaymentStatusEnumAccepted, nil
	case "success":
		return CryptopayPaymentStatusEnumSuccess, nil
	case "failed":
		return CryptopayPaymentStatusEnumFailed, nil
	}
	var t CryptopayPaymentStatusEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayPaymentStatusEnum) Ptr() *CryptopayPaymentStatusEnum {
	return &c
}

// overpaid / underpaid: more or less than the requested amount was received. partiallyPaid: payment expired with a partial payment that never reached acceptance.
type CryptopayPaymentSubStatusEnum string

const (
	CryptopayPaymentSubStatusEnumCreated         CryptopayPaymentSubStatusEnum = "created"
	CryptopayPaymentSubStatusEnumActivated       CryptopayPaymentSubStatusEnum = "activated"
	CryptopayPaymentSubStatusEnumAwaitingPayment CryptopayPaymentSubStatusEnum = "awaitingPayment"
	CryptopayPaymentSubStatusEnumConfirming      CryptopayPaymentSubStatusEnum = "confirming"
	CryptopayPaymentSubStatusEnumCompleted       CryptopayPaymentSubStatusEnum = "completed"
	CryptopayPaymentSubStatusEnumOverpaid        CryptopayPaymentSubStatusEnum = "overpaid"
	CryptopayPaymentSubStatusEnumUnderpaid       CryptopayPaymentSubStatusEnum = "underpaid"
	CryptopayPaymentSubStatusEnumExpired         CryptopayPaymentSubStatusEnum = "expired"
	CryptopayPaymentSubStatusEnumCancelled       CryptopayPaymentSubStatusEnum = "cancelled"
	CryptopayPaymentSubStatusEnumPartiallyPaid   CryptopayPaymentSubStatusEnum = "partiallyPaid"
)

func NewCryptopayPaymentSubStatusEnumFromString(s string) (CryptopayPaymentSubStatusEnum, error) {
	switch s {
	case "created":
		return CryptopayPaymentSubStatusEnumCreated, nil
	case "activated":
		return CryptopayPaymentSubStatusEnumActivated, nil
	case "awaitingPayment":
		return CryptopayPaymentSubStatusEnumAwaitingPayment, nil
	case "confirming":
		return CryptopayPaymentSubStatusEnumConfirming, nil
	case "completed":
		return CryptopayPaymentSubStatusEnumCompleted, nil
	case "overpaid":
		return CryptopayPaymentSubStatusEnumOverpaid, nil
	case "underpaid":
		return CryptopayPaymentSubStatusEnumUnderpaid, nil
	case "expired":
		return CryptopayPaymentSubStatusEnumExpired, nil
	case "cancelled":
		return CryptopayPaymentSubStatusEnumCancelled, nil
	case "partiallyPaid":
		return CryptopayPaymentSubStatusEnumPartiallyPaid, nil
	}
	var t CryptopayPaymentSubStatusEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayPaymentSubStatusEnum) Ptr() *CryptopayPaymentSubStatusEnum {
	return &c
}

var (
	cryptopayPublicPaymentResponseFieldActivatedAt           = big.NewInt(1 << 0)
	cryptopayPublicPaymentResponseFieldActivationFlowSeconds = big.NewInt(1 << 1)
	cryptopayPublicPaymentResponseFieldAddress               = big.NewInt(1 << 2)
	cryptopayPublicPaymentResponseFieldAmount                = big.NewInt(1 << 3)
	cryptopayPublicPaymentResponseFieldAmountReceived        = big.NewInt(1 << 4)
	cryptopayPublicPaymentResponseFieldAsset                 = big.NewInt(1 << 5)
	cryptopayPublicPaymentResponseFieldCreatedAt             = big.NewInt(1 << 6)
	cryptopayPublicPaymentResponseFieldExpiresAt             = big.NewInt(1 << 7)
	cryptopayPublicPaymentResponseFieldID                    = big.NewInt(1 << 8)
	cryptopayPublicPaymentResponseFieldPaymentWindowSeconds  = big.NewInt(1 << 9)
	cryptopayPublicPaymentResponseFieldRedirect              = big.NewInt(1 << 10)
	cryptopayPublicPaymentResponseFieldStatus                = big.NewInt(1 << 11)
	cryptopayPublicPaymentResponseFieldSubStatus             = big.NewInt(1 << 12)
	cryptopayPublicPaymentResponseFieldUnderpaymentTolerance = big.NewInt(1 << 13)
	cryptopayPublicPaymentResponseFieldUpdatedAt             = big.NewInt(1 << 14)
	cryptopayPublicPaymentResponseFieldPaymentPageURL        = big.NewInt(1 << 15)
)

type CryptopayPublicPaymentResponse struct {
	ActivatedAt           *int    `json:"activatedAt,omitempty" url:"activatedAt,omitempty"`
	ActivationFlowSeconds *int    `json:"activationFlowSeconds,omitempty" url:"activationFlowSeconds,omitempty"`
	Address               *string `json:"address,omitempty" url:"address,omitempty"`
	// Integer string in the asset's smallest unit.
	Amount *string `json:"amount,omitempty" url:"amount,omitempty"`
	// Integer string in the asset's smallest unit.
	AmountReceived       *string                        `json:"amountReceived,omitempty" url:"amountReceived,omitempty"`
	Asset                *CryptopayAssetID              `json:"asset,omitempty" url:"asset,omitempty"`
	CreatedAt            *int                           `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	ExpiresAt            *int                           `json:"expiresAt,omitempty" url:"expiresAt,omitempty"`
	ID                   *string                        `json:"id,omitempty" url:"id,omitempty"`
	PaymentWindowSeconds *int                           `json:"paymentWindowSeconds,omitempty" url:"paymentWindowSeconds,omitempty"`
	Redirect             *CryptopayPublicRedirect       `json:"redirect,omitempty" url:"redirect,omitempty"`
	Status               *CryptopayPaymentStatusEnum    `json:"status,omitempty" url:"status,omitempty"`
	SubStatus            *CryptopayPaymentSubStatusEnum `json:"subStatus,omitempty" url:"subStatus,omitempty"`
	// Integer string in the asset's smallest unit.
	UnderpaymentTolerance *string `json:"underpaymentTolerance,omitempty" url:"underpaymentTolerance,omitempty"`
	UpdatedAt             *int    `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`
	// Absolute URL of the Suward-hosted checkout page where the customer pays this payment.
	PaymentPageURL *string `json:"paymentPageUrl,omitempty" url:"paymentPageUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayPublicPaymentResponse) GetActivatedAt() *int {
	if c == nil {
		return nil
	}
	return c.ActivatedAt
}

func (c *CryptopayPublicPaymentResponse) GetActivationFlowSeconds() *int {
	if c == nil {
		return nil
	}
	return c.ActivationFlowSeconds
}

func (c *CryptopayPublicPaymentResponse) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CryptopayPublicPaymentResponse) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CryptopayPublicPaymentResponse) GetAmountReceived() *string {
	if c == nil {
		return nil
	}
	return c.AmountReceived
}

func (c *CryptopayPublicPaymentResponse) GetAsset() *CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.Asset
}

func (c *CryptopayPublicPaymentResponse) GetCreatedAt() *int {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CryptopayPublicPaymentResponse) GetExpiresAt() *int {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CryptopayPublicPaymentResponse) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CryptopayPublicPaymentResponse) GetPaymentWindowSeconds() *int {
	if c == nil {
		return nil
	}
	return c.PaymentWindowSeconds
}

func (c *CryptopayPublicPaymentResponse) GetRedirect() *CryptopayPublicRedirect {
	if c == nil {
		return nil
	}
	return c.Redirect
}

func (c *CryptopayPublicPaymentResponse) GetStatus() *CryptopayPaymentStatusEnum {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CryptopayPublicPaymentResponse) GetSubStatus() *CryptopayPaymentSubStatusEnum {
	if c == nil {
		return nil
	}
	return c.SubStatus
}

func (c *CryptopayPublicPaymentResponse) GetUnderpaymentTolerance() *string {
	if c == nil {
		return nil
	}
	return c.UnderpaymentTolerance
}

func (c *CryptopayPublicPaymentResponse) GetUpdatedAt() *int {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CryptopayPublicPaymentResponse) GetPaymentPageURL() *string {
	if c == nil {
		return nil
	}
	return c.PaymentPageURL
}

func (c *CryptopayPublicPaymentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayPublicPaymentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActivatedAt sets the ActivatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetActivatedAt(activatedAt *int) {
	c.ActivatedAt = activatedAt
	c.require(cryptopayPublicPaymentResponseFieldActivatedAt)
}

// SetActivationFlowSeconds sets the ActivationFlowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetActivationFlowSeconds(activationFlowSeconds *int) {
	c.ActivationFlowSeconds = activationFlowSeconds
	c.require(cryptopayPublicPaymentResponseFieldActivationFlowSeconds)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAddress(address *string) {
	c.Address = address
	c.require(cryptopayPublicPaymentResponseFieldAddress)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopayPublicPaymentResponseFieldAmount)
}

// SetAmountReceived sets the AmountReceived field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAmountReceived(amountReceived *string) {
	c.AmountReceived = amountReceived
	c.require(cryptopayPublicPaymentResponseFieldAmountReceived)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayPublicPaymentResponseFieldAsset)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetCreatedAt(createdAt *int) {
	c.CreatedAt = createdAt
	c.require(cryptopayPublicPaymentResponseFieldCreatedAt)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetExpiresAt(expiresAt *int) {
	c.ExpiresAt = expiresAt
	c.require(cryptopayPublicPaymentResponseFieldExpiresAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetID(id *string) {
	c.ID = id
	c.require(cryptopayPublicPaymentResponseFieldID)
}

// SetPaymentWindowSeconds sets the PaymentWindowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetPaymentWindowSeconds(paymentWindowSeconds *int) {
	c.PaymentWindowSeconds = paymentWindowSeconds
	c.require(cryptopayPublicPaymentResponseFieldPaymentWindowSeconds)
}

// SetRedirect sets the Redirect field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetRedirect(redirect *CryptopayPublicRedirect) {
	c.Redirect = redirect
	c.require(cryptopayPublicPaymentResponseFieldRedirect)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetStatus(status *CryptopayPaymentStatusEnum) {
	c.Status = status
	c.require(cryptopayPublicPaymentResponseFieldStatus)
}

// SetSubStatus sets the SubStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetSubStatus(subStatus *CryptopayPaymentSubStatusEnum) {
	c.SubStatus = subStatus
	c.require(cryptopayPublicPaymentResponseFieldSubStatus)
}

// SetUnderpaymentTolerance sets the UnderpaymentTolerance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetUnderpaymentTolerance(underpaymentTolerance *string) {
	c.UnderpaymentTolerance = underpaymentTolerance
	c.require(cryptopayPublicPaymentResponseFieldUnderpaymentTolerance)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetUpdatedAt(updatedAt *int) {
	c.UpdatedAt = updatedAt
	c.require(cryptopayPublicPaymentResponseFieldUpdatedAt)
}

// SetPaymentPageURL sets the PaymentPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetPaymentPageURL(paymentPageURL *string) {
	c.PaymentPageURL = paymentPageURL
	c.require(cryptopayPublicPaymentResponseFieldPaymentPageURL)
}

func (c *CryptopayPublicPaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayPublicPaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayPublicPaymentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayPublicPaymentResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayPublicPaymentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayPublicPaymentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayPublicRedirectFieldQuery = big.NewInt(1 << 0)
	cryptopayPublicRedirectFieldURL   = big.NewInt(1 << 1)
)

type CryptopayPublicRedirect struct {
	Query map[string]string `json:"query,omitempty" url:"query,omitempty"`
	URL   *string           `json:"url,omitempty" url:"url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayPublicRedirect) GetQuery() map[string]string {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *CryptopayPublicRedirect) GetURL() *string {
	if c == nil {
		return nil
	}
	return c.URL
}

func (c *CryptopayPublicRedirect) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayPublicRedirect) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicRedirect) SetQuery(query map[string]string) {
	c.Query = query
	c.require(cryptopayPublicRedirectFieldQuery)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicRedirect) SetURL(url *string) {
	c.URL = url
	c.require(cryptopayPublicRedirectFieldURL)
}

func (c *CryptopayPublicRedirect) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayPublicRedirect
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayPublicRedirect(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayPublicRedirect) MarshalJSON() ([]byte, error) {
	type embed CryptopayPublicRedirect
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayPublicRedirect) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayQuotePaymentResponseFieldAsset       = big.NewInt(1 << 0)
	cryptopayQuotePaymentResponseFieldAmount      = big.NewInt(1 << 1)
	cryptopayQuotePaymentResponseFieldFee         = big.NewInt(1 << 2)
	cryptopayQuotePaymentResponseFieldNetworkFee  = big.NewInt(1 << 3)
	cryptopayQuotePaymentResponseFieldNetAmount   = big.NewInt(1 << 4)
	cryptopayQuotePaymentResponseFieldGross       = big.NewInt(1 << 5)
	cryptopayQuotePaymentResponseFieldQuotedPrice = big.NewInt(1 << 6)
)

type CryptopayQuotePaymentResponse struct {
	Asset *CryptopayAssetID `json:"asset,omitempty" url:"asset,omitempty"`
	// Gross amount, integer string in the asset's smallest unit.
	Amount *string `json:"amount,omitempty" url:"amount,omitempty"`
	// Platform fee: 0.4% of the amount, minimum $1 equivalent. Integer string in the asset's smallest unit.
	Fee *string `json:"fee,omitempty" url:"fee,omitempty"`
	// Estimated on-chain (gas) cost, deducted from the received amount. Integer string in the asset's smallest unit.
	NetworkFee *string `json:"networkFee,omitempty" url:"networkFee,omitempty"`
	// Amount the merchant receives after all fees. Integer string in the asset's smallest unit.
	NetAmount *string `json:"netAmount,omitempty" url:"netAmount,omitempty"`
	// Amount the customer pays: base plus any customer-paid fees. Integer string in the asset's smallest unit.
	Gross *string `json:"gross,omitempty" url:"gross,omitempty"`
	// USD price used for this quote, decimal string. Not locked — the binding price is captured when the payment is created.
	QuotedPrice *string `json:"quotedPrice,omitempty" url:"quotedPrice,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayQuotePaymentResponse) GetAsset() *CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.Asset
}

func (c *CryptopayQuotePaymentResponse) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CryptopayQuotePaymentResponse) GetFee() *string {
	if c == nil {
		return nil
	}
	return c.Fee
}

func (c *CryptopayQuotePaymentResponse) GetNetworkFee() *string {
	if c == nil {
		return nil
	}
	return c.NetworkFee
}

func (c *CryptopayQuotePaymentResponse) GetNetAmount() *string {
	if c == nil {
		return nil
	}
	return c.NetAmount
}

func (c *CryptopayQuotePaymentResponse) GetGross() *string {
	if c == nil {
		return nil
	}
	return c.Gross
}

func (c *CryptopayQuotePaymentResponse) GetQuotedPrice() *string {
	if c == nil {
		return nil
	}
	return c.QuotedPrice
}

func (c *CryptopayQuotePaymentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayQuotePaymentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayQuotePaymentResponseFieldAsset)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopayQuotePaymentResponseFieldAmount)
}

// SetFee sets the Fee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetFee(fee *string) {
	c.Fee = fee
	c.require(cryptopayQuotePaymentResponseFieldFee)
}

// SetNetworkFee sets the NetworkFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetNetworkFee(networkFee *string) {
	c.NetworkFee = networkFee
	c.require(cryptopayQuotePaymentResponseFieldNetworkFee)
}

// SetNetAmount sets the NetAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetNetAmount(netAmount *string) {
	c.NetAmount = netAmount
	c.require(cryptopayQuotePaymentResponseFieldNetAmount)
}

// SetGross sets the Gross field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetGross(gross *string) {
	c.Gross = gross
	c.require(cryptopayQuotePaymentResponseFieldGross)
}

// SetQuotedPrice sets the QuotedPrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetQuotedPrice(quotedPrice *string) {
	c.QuotedPrice = quotedPrice
	c.require(cryptopayQuotePaymentResponseFieldQuotedPrice)
}

func (c *CryptopayQuotePaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayQuotePaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayQuotePaymentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayQuotePaymentResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayQuotePaymentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayQuotePaymentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayRedirectConfigDtoFieldData   = big.NewInt(1 << 0)
	cryptopayRedirectConfigDtoFieldParams = big.NewInt(1 << 1)
	cryptopayRedirectConfigDtoFieldURL    = big.NewInt(1 << 2)
)

type CryptopayRedirectConfigDto struct {
	Data   *string                                `json:"data,omitempty" url:"data,omitempty"`
	Params []CryptopayRedirectConfigDtoParamsItem `json:"params,omitempty" url:"params,omitempty"`
	URL    *string                                `json:"url,omitempty" url:"url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayRedirectConfigDto) GetData() *string {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CryptopayRedirectConfigDto) GetParams() []CryptopayRedirectConfigDtoParamsItem {
	if c == nil {
		return nil
	}
	return c.Params
}

func (c *CryptopayRedirectConfigDto) GetURL() *string {
	if c == nil {
		return nil
	}
	return c.URL
}

func (c *CryptopayRedirectConfigDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayRedirectConfigDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayRedirectConfigDto) SetData(data *string) {
	c.Data = data
	c.require(cryptopayRedirectConfigDtoFieldData)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayRedirectConfigDto) SetParams(params []CryptopayRedirectConfigDtoParamsItem) {
	c.Params = params
	c.require(cryptopayRedirectConfigDtoFieldParams)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayRedirectConfigDto) SetURL(url *string) {
	c.URL = url
	c.require(cryptopayRedirectConfigDtoFieldURL)
}

func (c *CryptopayRedirectConfigDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayRedirectConfigDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayRedirectConfigDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayRedirectConfigDto) MarshalJSON() ([]byte, error) {
	type embed CryptopayRedirectConfigDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayRedirectConfigDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CryptopayRedirectConfigDtoParamsItem string

const (
	CryptopayRedirectConfigDtoParamsItemID         CryptopayRedirectConfigDtoParamsItem = "id"
	CryptopayRedirectConfigDtoParamsItemExternalID CryptopayRedirectConfigDtoParamsItem = "externalId"
)

func NewCryptopayRedirectConfigDtoParamsItemFromString(s string) (CryptopayRedirectConfigDtoParamsItem, error) {
	switch s {
	case "id":
		return CryptopayRedirectConfigDtoParamsItemID, nil
	case "externalId":
		return CryptopayRedirectConfigDtoParamsItemExternalID, nil
	}
	var t CryptopayRedirectConfigDtoParamsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayRedirectConfigDtoParamsItem) Ptr() *CryptopayRedirectConfigDtoParamsItem {
	return &c
}

var (
	cryptopayTransactionResponseFieldAcceptedAt = big.NewInt(1 << 0)
	cryptopayTransactionResponseFieldAmount     = big.NewInt(1 << 1)
	cryptopayTransactionResponseFieldDetectedAt = big.NewInt(1 << 2)
	cryptopayTransactionResponseFieldTxHash     = big.NewInt(1 << 3)
)

type CryptopayTransactionResponse struct {
	AcceptedAt *int    `json:"acceptedAt,omitempty" url:"acceptedAt,omitempty"`
	Amount     *string `json:"amount,omitempty" url:"amount,omitempty"`
	DetectedAt *int    `json:"detectedAt,omitempty" url:"detectedAt,omitempty"`
	TxHash     *string `json:"txHash,omitempty" url:"txHash,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayTransactionResponse) GetAcceptedAt() *int {
	if c == nil {
		return nil
	}
	return c.AcceptedAt
}

func (c *CryptopayTransactionResponse) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CryptopayTransactionResponse) GetDetectedAt() *int {
	if c == nil {
		return nil
	}
	return c.DetectedAt
}

func (c *CryptopayTransactionResponse) GetTxHash() *string {
	if c == nil {
		return nil
	}
	return c.TxHash
}

func (c *CryptopayTransactionResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayTransactionResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAcceptedAt sets the AcceptedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetAcceptedAt(acceptedAt *int) {
	c.AcceptedAt = acceptedAt
	c.require(cryptopayTransactionResponseFieldAcceptedAt)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopayTransactionResponseFieldAmount)
}

// SetDetectedAt sets the DetectedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetDetectedAt(detectedAt *int) {
	c.DetectedAt = detectedAt
	c.require(cryptopayTransactionResponseFieldDetectedAt)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetTxHash(txHash *string) {
	c.TxHash = txHash
	c.require(cryptopayTransactionResponseFieldTxHash)
}

func (c *CryptopayTransactionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayTransactionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayTransactionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayTransactionResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayTransactionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayTransactionResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type GetV1PaymentsPaymentIDResponse struct {
	CryptopayPaymentResponse       *CryptopayPaymentResponse
	CryptopayPublicPaymentResponse *CryptopayPublicPaymentResponse

	typ string
}

func (g *GetV1PaymentsPaymentIDResponse) GetCryptopayPaymentResponse() *CryptopayPaymentResponse {
	if g == nil {
		return nil
	}
	return g.CryptopayPaymentResponse
}

func (g *GetV1PaymentsPaymentIDResponse) GetCryptopayPublicPaymentResponse() *CryptopayPublicPaymentResponse {
	if g == nil {
		return nil
	}
	return g.CryptopayPublicPaymentResponse
}

func (g *GetV1PaymentsPaymentIDResponse) UnmarshalJSON(data []byte) error {
	valueCryptopayPaymentResponse := new(CryptopayPaymentResponse)
	if err := json.Unmarshal(data, &valueCryptopayPaymentResponse); err == nil {
		g.typ = "CryptopayPaymentResponse"
		g.CryptopayPaymentResponse = valueCryptopayPaymentResponse
		return nil
	}
	valueCryptopayPublicPaymentResponse := new(CryptopayPublicPaymentResponse)
	if err := json.Unmarshal(data, &valueCryptopayPublicPaymentResponse); err == nil {
		g.typ = "CryptopayPublicPaymentResponse"
		g.CryptopayPublicPaymentResponse = valueCryptopayPublicPaymentResponse
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetV1PaymentsPaymentIDResponse) MarshalJSON() ([]byte, error) {
	if g.typ == "CryptopayPaymentResponse" || g.CryptopayPaymentResponse != nil {
		return json.Marshal(g.CryptopayPaymentResponse)
	}
	if g.typ == "CryptopayPublicPaymentResponse" || g.CryptopayPublicPaymentResponse != nil {
		return json.Marshal(g.CryptopayPublicPaymentResponse)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetV1PaymentsPaymentIDResponseVisitor interface {
	VisitCryptopayPaymentResponse(*CryptopayPaymentResponse) error
	VisitCryptopayPublicPaymentResponse(*CryptopayPublicPaymentResponse) error
}

func (g *GetV1PaymentsPaymentIDResponse) Accept(visitor GetV1PaymentsPaymentIDResponseVisitor) error {
	if g.typ == "CryptopayPaymentResponse" || g.CryptopayPaymentResponse != nil {
		return visitor.VisitCryptopayPaymentResponse(g.CryptopayPaymentResponse)
	}
	if g.typ == "CryptopayPublicPaymentResponse" || g.CryptopayPublicPaymentResponse != nil {
		return visitor.VisitCryptopayPublicPaymentResponse(g.CryptopayPublicPaymentResponse)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetV1PaymentsRequestOrder string

const (
	GetV1PaymentsRequestOrderAsc  GetV1PaymentsRequestOrder = "asc"
	GetV1PaymentsRequestOrderDesc GetV1PaymentsRequestOrder = "desc"
)

func NewGetV1PaymentsRequestOrderFromString(s string) (GetV1PaymentsRequestOrder, error) {
	switch s {
	case "asc":
		return GetV1PaymentsRequestOrderAsc, nil
	case "desc":
		return GetV1PaymentsRequestOrderDesc, nil
	}
	var t GetV1PaymentsRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetV1PaymentsRequestOrder) Ptr() *GetV1PaymentsRequestOrder {
	return &g
}
