// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	big "math/big"
)

var (
	postV1PaymentsPaymentIDActivateRequestFieldPaymentID = big.NewInt(1 << 0)
)

type PostV1PaymentsPaymentIDActivateRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostV1PaymentsPaymentIDActivateRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PaymentsPaymentIDActivateRequest) SetPaymentID(paymentID string) {
	p.PaymentID = paymentID
	p.require(postV1PaymentsPaymentIDActivateRequestFieldPaymentID)
}

var (
	postV1PaymentsPaymentIDCancelRequestFieldPaymentID = big.NewInt(1 << 0)
)

type PostV1PaymentsPaymentIDCancelRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostV1PaymentsPaymentIDCancelRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostV1PaymentsPaymentIDCancelRequest) SetPaymentID(paymentID string) {
	p.PaymentID = paymentID
	p.require(postV1PaymentsPaymentIDCancelRequestFieldPaymentID)
}

var (
	cryptopayCreatePaymentRequestFieldActivationFlowSeconds = big.NewInt(1 << 0)
	cryptopayCreatePaymentRequestFieldAmount                = big.NewInt(1 << 1)
	cryptopayCreatePaymentRequestFieldAsset                 = big.NewInt(1 << 2)
	cryptopayCreatePaymentRequestFieldNetworkFeePayer       = big.NewInt(1 << 3)
	cryptopayCreatePaymentRequestFieldServiceFeePayer       = big.NewInt(1 << 4)
	cryptopayCreatePaymentRequestFieldComplianceLevel       = big.NewInt(1 << 5)
	cryptopayCreatePaymentRequestFieldExternalID            = big.NewInt(1 << 6)
	cryptopayCreatePaymentRequestFieldMetadata              = big.NewInt(1 << 7)
	cryptopayCreatePaymentRequestFieldPaymentWindowSeconds  = big.NewInt(1 << 8)
	cryptopayCreatePaymentRequestFieldRedirectConfig        = big.NewInt(1 << 9)
	cryptopayCreatePaymentRequestFieldUnderpaymentTolerance = big.NewInt(1 << 10)
	cryptopayCreatePaymentRequestFieldWebhookURL            = big.NewInt(1 << 11)
)

type CryptopayCreatePaymentRequest struct {
	// Grace period in seconds before the payment window starts counting, giving the customer time to open the checkout before the timer runs. Optional; range 1 to 3600 (1 hour).
	ActivationFlowSeconds *int `json:"activationFlowSeconds,omitempty" url:"-"`
	// Merchant base amount, integer string in the asset's smallest unit. When a fee payer is customer the customer is charged more than this (gross); when merchant (default) the fee is deducted from the merchant's proceeds.
	Amount string `json:"amount" url:"-"`
	// Asset the customer will pay in, as an asset id-string (e.g. USDT_ARBITRUM). Required only when the project allows more than one asset; when the project has a single asset it may be omitted. The full set of accepted values is served live at GET /v1/assets.
	Asset *CryptopayAssetID `json:"asset,omitempty" url:"-"`
	// Who bears the network (gas) fee. Default merchant.
	NetworkFeePayer *CryptopayFeePayer `json:"networkFeePayer,omitempty" url:"-"`
	// Who bears the platform (service) fee. Default merchant.
	ServiceFeePayer *CryptopayFeePayer `json:"serviceFeePayer,omitempty" url:"-"`
	// AML screening depth: basic (free, no minimum fee) or extended ($0.45 minimum fee). Omit to inherit the project/org default (extended).
	ComplianceLevel *CryptopayComplianceLevel `json:"complianceLevel,omitempty" url:"-"`
	// Your own identifier for this payment. Echoed back on the payment and its webhooks, and can be appended to the return URL as a redirect parameter. Optional.
	ExternalID *string `json:"externalId,omitempty" url:"-"`
	// Arbitrary JSON key/value data to attach to the payment. Stored and echoed back unchanged on the payment and its webhooks; never sent on-chain. Use it to correlate the payment with your own records.
	Metadata map[string]any `json:"metadata,omitempty" url:"-"`
	// How long the payment stays open for funding, in seconds. Optional; when omitted the project default applies. Range 300 (5 minutes) to 86400 (24 hours).
	PaymentWindowSeconds *int `json:"paymentWindowSeconds,omitempty" url:"-"`
	// Optional "return to store" redirect configuration: the base URL the customer is sent back to after paying, plus which payment identifiers to append as query parameters.
	RedirectConfig *CryptopayRedirectConfigDto `json:"redirectConfig,omitempty" url:"-"`
	// Amount the customer may underpay and still have the payment accepted, as an integer string in the asset's smallest unit (same scale as amount). Optional; if set it must be >= 0 and strictly less than amount. Default 0 (exact amount required). Example: for amount "10000000" (10 USDT) a value of "500000" allows a 0.50 USDT shortfall.
	UnderpaymentTolerance *string `json:"underpaymentTolerance,omitempty" url:"-"`
	// Webhook URL to receive this payment's events. Optional; overrides the project's default webhook URL for this payment only.
	WebhookURL *string `json:"webhookUrl,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopayCreatePaymentRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActivationFlowSeconds sets the ActivationFlowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetActivationFlowSeconds(activationFlowSeconds *int) {
	c.ActivationFlowSeconds = activationFlowSeconds
	c.require(cryptopayCreatePaymentRequestFieldActivationFlowSeconds)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetAmount(amount string) {
	c.Amount = amount
	c.require(cryptopayCreatePaymentRequestFieldAmount)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayCreatePaymentRequestFieldAsset)
}

// SetNetworkFeePayer sets the NetworkFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetNetworkFeePayer(networkFeePayer *CryptopayFeePayer) {
	c.NetworkFeePayer = networkFeePayer
	c.require(cryptopayCreatePaymentRequestFieldNetworkFeePayer)
}

// SetServiceFeePayer sets the ServiceFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetServiceFeePayer(serviceFeePayer *CryptopayFeePayer) {
	c.ServiceFeePayer = serviceFeePayer
	c.require(cryptopayCreatePaymentRequestFieldServiceFeePayer)
}

// SetComplianceLevel sets the ComplianceLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetComplianceLevel(complianceLevel *CryptopayComplianceLevel) {
	c.ComplianceLevel = complianceLevel
	c.require(cryptopayCreatePaymentRequestFieldComplianceLevel)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(cryptopayCreatePaymentRequestFieldExternalID)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(cryptopayCreatePaymentRequestFieldMetadata)
}

// SetPaymentWindowSeconds sets the PaymentWindowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetPaymentWindowSeconds(paymentWindowSeconds *int) {
	c.PaymentWindowSeconds = paymentWindowSeconds
	c.require(cryptopayCreatePaymentRequestFieldPaymentWindowSeconds)
}

// SetRedirectConfig sets the RedirectConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetRedirectConfig(redirectConfig *CryptopayRedirectConfigDto) {
	c.RedirectConfig = redirectConfig
	c.require(cryptopayCreatePaymentRequestFieldRedirectConfig)
}

// SetUnderpaymentTolerance sets the UnderpaymentTolerance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetUnderpaymentTolerance(underpaymentTolerance *string) {
	c.UnderpaymentTolerance = underpaymentTolerance
	c.require(cryptopayCreatePaymentRequestFieldUnderpaymentTolerance)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreatePaymentRequest) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cryptopayCreatePaymentRequestFieldWebhookURL)
}

func (c *CryptopayCreatePaymentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayCreatePaymentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopayCreatePaymentRequest(body)
	return nil
}

func (c *CryptopayCreatePaymentRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopayCreatePaymentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getV1PaymentsPaymentIDRequestFieldPaymentID = big.NewInt(1 << 0)
)

type GetV1PaymentsPaymentIDRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1PaymentsPaymentIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsPaymentIDRequest) SetPaymentID(paymentID string) {
	g.PaymentID = paymentID
	g.require(getV1PaymentsPaymentIDRequestFieldPaymentID)
}

var (
	getV1PaymentsPaymentIDTransactionsRequestFieldPaymentID = big.NewInt(1 << 0)
	getV1PaymentsPaymentIDTransactionsRequestFieldOrder     = big.NewInt(1 << 1)
	getV1PaymentsPaymentIDTransactionsRequestFieldLimit     = big.NewInt(1 << 2)
	getV1PaymentsPaymentIDTransactionsRequestFieldLastID    = big.NewInt(1 << 3)
)

type GetV1PaymentsPaymentIDTransactionsRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`
	// Sort order by id: asc = ascending, anything else = descending
	Order *GetV1PaymentsPaymentIDTransactionsRequestOrder `json:"-" url:"order,omitempty"`
	// Page size (default 20, max 100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Pagination cursor: last id from the previous page
	LastID *string `json:"-" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1PaymentsPaymentIDTransactionsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsPaymentIDTransactionsRequest) SetPaymentID(paymentID string) {
	g.PaymentID = paymentID
	g.require(getV1PaymentsPaymentIDTransactionsRequestFieldPaymentID)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsPaymentIDTransactionsRequest) SetOrder(order *GetV1PaymentsPaymentIDTransactionsRequestOrder) {
	g.Order = order
	g.require(getV1PaymentsPaymentIDTransactionsRequestFieldOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsPaymentIDTransactionsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getV1PaymentsPaymentIDTransactionsRequestFieldLimit)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsPaymentIDTransactionsRequest) SetLastID(lastID *string) {
	g.LastID = lastID
	g.require(getV1PaymentsPaymentIDTransactionsRequestFieldLastID)
}

var (
	getV1PaymentsRequestFieldOrder  = big.NewInt(1 << 0)
	getV1PaymentsRequestFieldLimit  = big.NewInt(1 << 1)
	getV1PaymentsRequestFieldLastID = big.NewInt(1 << 2)
)

type GetV1PaymentsRequest struct {
	// Sort order (asc/desc)
	Order *GetV1PaymentsRequestOrder `json:"-" url:"order,omitempty"`
	// Limit (default 20, max 100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Last ID for pagination
	LastID *string `json:"-" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1PaymentsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsRequest) SetOrder(order *GetV1PaymentsRequestOrder) {
	g.Order = order
	g.require(getV1PaymentsRequestFieldOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getV1PaymentsRequestFieldLimit)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1PaymentsRequest) SetLastID(lastID *string) {
	g.LastID = lastID
	g.require(getV1PaymentsRequestFieldLastID)
}

var (
	cryptopayQuotePaymentRequestFieldAsset           = big.NewInt(1 << 0)
	cryptopayQuotePaymentRequestFieldAmount          = big.NewInt(1 << 1)
	cryptopayQuotePaymentRequestFieldNetworkFeePayer = big.NewInt(1 << 2)
	cryptopayQuotePaymentRequestFieldServiceFeePayer = big.NewInt(1 << 3)
	cryptopayQuotePaymentRequestFieldComplianceLevel = big.NewInt(1 << 4)
)

type CryptopayQuotePaymentRequest struct {
	// Asset identifier (see GET /v1/assets for the live list).
	Asset CryptopayAssetID `json:"asset" url:"-"`
	// Merchant base amount, integer string in the asset's smallest unit. Example: "5000000" = 5 USDT. The response returns the derived gross (what the customer pays) and netAmount (what the merchant receives).
	Amount string `json:"amount" url:"-"`
	// Who bears the network (gas) fee. Default merchant.
	NetworkFeePayer *CryptopayFeePayer `json:"networkFeePayer,omitempty" url:"-"`
	// Who bears the platform (service) fee. Default merchant.
	ServiceFeePayer *CryptopayFeePayer `json:"serviceFeePayer,omitempty" url:"-"`
	// AML screening depth to quote: basic (free, no minimum fee) or extended ($0.45 minimum fee). Omit to inherit the project/org default (extended).
	ComplianceLevel *CryptopayComplianceLevel `json:"complianceLevel,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopayQuotePaymentRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetAsset(asset CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayQuotePaymentRequestFieldAsset)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetAmount(amount string) {
	c.Amount = amount
	c.require(cryptopayQuotePaymentRequestFieldAmount)
}

// SetNetworkFeePayer sets the NetworkFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetNetworkFeePayer(networkFeePayer *CryptopayFeePayer) {
	c.NetworkFeePayer = networkFeePayer
	c.require(cryptopayQuotePaymentRequestFieldNetworkFeePayer)
}

// SetServiceFeePayer sets the ServiceFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetServiceFeePayer(serviceFeePayer *CryptopayFeePayer) {
	c.ServiceFeePayer = serviceFeePayer
	c.require(cryptopayQuotePaymentRequestFieldServiceFeePayer)
}

// SetComplianceLevel sets the ComplianceLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentRequest) SetComplianceLevel(complianceLevel *CryptopayComplianceLevel) {
	c.ComplianceLevel = complianceLevel
	c.require(cryptopayQuotePaymentRequestFieldComplianceLevel)
}

func (c *CryptopayQuotePaymentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayQuotePaymentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopayQuotePaymentRequest(body)
	return nil
}

func (c *CryptopayQuotePaymentRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopayQuotePaymentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	cryptopaySimulatePaymentRequestFieldPaymentID = big.NewInt(1 << 0)
	cryptopaySimulatePaymentRequestFieldAmount    = big.NewInt(1 << 1)
	cryptopaySimulatePaymentRequestFieldStatus    = big.NewInt(1 << 2)
	cryptopaySimulatePaymentRequestFieldSubStatus = big.NewInt(1 << 3)
)

type CryptopaySimulatePaymentRequest struct {
	// Payment ID
	PaymentID string `json:"-" url:"-"`
	// Optional simulated received amount, integer string in the asset's smallest unit (see CreatePaymentRequest.amount).
	Amount *string `json:"amount,omitempty" url:"-"`
	// Target main status. Required — status and subStatus are independent axes, both must be supplied.
	Status CryptopayPaymentStatusEnum `json:"status" url:"-"`
	// Target sub-status (amount/detail axis). Required — status and subStatus are independent axes, both must be supplied.
	SubStatus CryptopayPaymentSubStatusEnum `json:"subStatus" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopaySimulatePaymentRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPaymentID sets the PaymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulatePaymentRequest) SetPaymentID(paymentID string) {
	c.PaymentID = paymentID
	c.require(cryptopaySimulatePaymentRequestFieldPaymentID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulatePaymentRequest) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopaySimulatePaymentRequestFieldAmount)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulatePaymentRequest) SetStatus(status CryptopayPaymentStatusEnum) {
	c.Status = status
	c.require(cryptopaySimulatePaymentRequestFieldStatus)
}

// SetSubStatus sets the SubStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulatePaymentRequest) SetSubStatus(subStatus CryptopayPaymentSubStatusEnum) {
	c.SubStatus = subStatus
	c.require(cryptopaySimulatePaymentRequestFieldSubStatus)
}

func (c *CryptopaySimulatePaymentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopaySimulatePaymentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopaySimulatePaymentRequest(body)
	return nil
}

func (c *CryptopaySimulatePaymentRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopaySimulatePaymentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// AML screening depth for a payment. extended (default) runs paid providers and carries the $0.45 minimum service fee; basic runs only free checks and waives the minimum fee (0.4% only).
type CryptopayComplianceLevel string

const (
	CryptopayComplianceLevelBasic    CryptopayComplianceLevel = "basic"
	CryptopayComplianceLevelExtended CryptopayComplianceLevel = "extended"
)

func NewCryptopayComplianceLevelFromString(s string) (CryptopayComplianceLevel, error) {
	switch s {
	case "basic":
		return CryptopayComplianceLevelBasic, nil
	case "extended":
		return CryptopayComplianceLevelExtended, nil
	}
	var t CryptopayComplianceLevel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayComplianceLevel) Ptr() *CryptopayComplianceLevel {
	return &c
}

// Who bears a fee: merchant = deducted from the merchant's proceeds (default); customer = added on top of the customer charge.
type CryptopayFeePayer string

const (
	CryptopayFeePayerMerchant CryptopayFeePayer = "merchant"
	CryptopayFeePayerCustomer CryptopayFeePayer = "customer"
)

func NewCryptopayFeePayerFromString(s string) (CryptopayFeePayer, error) {
	switch s {
	case "merchant":
		return CryptopayFeePayerMerchant, nil
	case "customer":
		return CryptopayFeePayerCustomer, nil
	}
	var t CryptopayFeePayer
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayFeePayer) Ptr() *CryptopayFeePayer {
	return &c
}

var (
	cryptopayListPaymentsResponseFieldHasMore = big.NewInt(1 << 0)
	cryptopayListPaymentsResponseFieldItems   = big.NewInt(1 << 1)
)

type CryptopayListPaymentsResponse struct {
	// True when more payments exist beyond this page. To fetch the next page, pass the last item's id as the lastId query parameter.
	HasMore bool `json:"hasMore" url:"hasMore"`
	// Page of payments, ordered per the request's order parameter.
	Items []*CryptopayPaymentResponse `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayListPaymentsResponse) GetHasMore() bool {
	if c == nil {
		return false
	}
	return c.HasMore
}

func (c *CryptopayListPaymentsResponse) GetItems() []*CryptopayPaymentResponse {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CryptopayListPaymentsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayListPaymentsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListPaymentsResponse) SetHasMore(hasMore bool) {
	c.HasMore = hasMore
	c.require(cryptopayListPaymentsResponseFieldHasMore)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListPaymentsResponse) SetItems(items []*CryptopayPaymentResponse) {
	c.Items = items
	c.require(cryptopayListPaymentsResponseFieldItems)
}

func (c *CryptopayListPaymentsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayListPaymentsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayListPaymentsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayListPaymentsResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayListPaymentsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayListPaymentsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayPaymentResponseFieldAcceptedAt            = big.NewInt(1 << 0)
	cryptopayPaymentResponseFieldActivatedAt           = big.NewInt(1 << 1)
	cryptopayPaymentResponseFieldActivationFlowSeconds = big.NewInt(1 << 2)
	cryptopayPaymentResponseFieldAddress               = big.NewInt(1 << 3)
	cryptopayPaymentResponseFieldAmount                = big.NewInt(1 << 4)
	cryptopayPaymentResponseFieldAmountConfirmed       = big.NewInt(1 << 5)
	cryptopayPaymentResponseFieldAmountReceived        = big.NewInt(1 << 6)
	cryptopayPaymentResponseFieldAsset                 = big.NewInt(1 << 7)
	cryptopayPaymentResponseFieldConfirmedAt           = big.NewInt(1 << 8)
	cryptopayPaymentResponseFieldCreatedAt             = big.NewInt(1 << 9)
	cryptopayPaymentResponseFieldExpiresAt             = big.NewInt(1 << 10)
	cryptopayPaymentResponseFieldExternalID            = big.NewInt(1 << 11)
	cryptopayPaymentResponseFieldComplianceLevel       = big.NewInt(1 << 12)
	cryptopayPaymentResponseFieldFee                   = big.NewInt(1 << 13)
	cryptopayPaymentResponseFieldID                    = big.NewInt(1 << 14)
	cryptopayPaymentResponseFieldMetadata              = big.NewInt(1 << 15)
	cryptopayPaymentResponseFieldNetworkFee            = big.NewInt(1 << 16)
	cryptopayPaymentResponseFieldServiceFeeBps         = big.NewInt(1 << 17)
	cryptopayPaymentResponseFieldServiceFeeMinUsd      = big.NewInt(1 << 18)
	cryptopayPaymentResponseFieldQuotedPrice           = big.NewInt(1 << 19)
	cryptopayPaymentResponseFieldNetworkFeePayer       = big.NewInt(1 << 20)
	cryptopayPaymentResponseFieldServiceFeePayer       = big.NewInt(1 << 21)
	cryptopayPaymentResponseFieldPaymentWindowSeconds  = big.NewInt(1 << 22)
	cryptopayPaymentResponseFieldProjectID             = big.NewInt(1 << 23)
	cryptopayPaymentResponseFieldRedirectConfig        = big.NewInt(1 << 24)
	cryptopayPaymentResponseFieldStatus                = big.NewInt(1 << 25)
	cryptopayPaymentResponseFieldSubStatus             = big.NewInt(1 << 26)
	cryptopayPaymentResponseFieldTransactions          = big.NewInt(1 << 27)
	cryptopayPaymentResponseFieldUnderpaymentTolerance = big.NewInt(1 << 28)
	cryptopayPaymentResponseFieldUpdatedAt             = big.NewInt(1 << 29)
	cryptopayPaymentResponseFieldWebhookURL            = big.NewInt(1 << 30)
	cryptopayPaymentResponseFieldPaymentPageURL        = big.NewInt(1 << 31)
)

type CryptopayPaymentResponse struct {
	// Unix-milliseconds timestamp when the payment reached the accepted state (safe confirmations, balance credited). Null before acceptance.
	AcceptedAt *int `json:"acceptedAt,omitempty" url:"acceptedAt,omitempty"`
	// Unix-milliseconds timestamp when the payment was activated and its payment window began counting. Null before activation.
	ActivatedAt *int `json:"activatedAt,omitempty" url:"activatedAt,omitempty"`
	// Resolved activation grace period, in seconds. Null when not configured.
	ActivationFlowSeconds *int `json:"activationFlowSeconds,omitempty" url:"activationFlowSeconds,omitempty"`
	// On-chain deposit address the customer must send funds to. Null until the payment is activated and an address is assigned.
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Integer string in the asset's smallest unit.
	Amount string `json:"amount" url:"amount"`
	// Integer string in the asset's smallest unit.
	AmountConfirmed string `json:"amountConfirmed" url:"amountConfirmed"`
	// Integer string in the asset's smallest unit.
	AmountReceived string `json:"amountReceived" url:"amountReceived"`
	// Asset the payment is denominated in, as an asset id-string (see GET /v1/assets). Null until an asset is selected for the payment.
	Asset *CryptopayAssetID `json:"asset,omitempty" url:"asset,omitempty"`
	// Unix-milliseconds timestamp when the payment reached finalization (confirmed). Null until confirmed; may revert if a chain reorg undoes the confirmation.
	ConfirmedAt *int `json:"confirmedAt,omitempty" url:"confirmedAt,omitempty"`
	// Unix-milliseconds timestamp when the payment was created.
	CreatedAt int `json:"createdAt" url:"createdAt"`
	// Unix-milliseconds timestamp when the payment window closes; the payment expires (fails) if it has not been paid by then.
	ExpiresAt int `json:"expiresAt" url:"expiresAt"`
	// Merchant's own identifier for this payment, echoed from creation. Null when none was provided.
	ExternalID *string `json:"externalId,omitempty" url:"externalId,omitempty"`
	// AML screening depth applied to this payment: basic (free, no fee floor) or extended ($0.45 floor).
	ComplianceLevel *CryptopayComplianceLevel `json:"complianceLevel,omitempty" url:"complianceLevel,omitempty"`
	// Platform fee, integer string in the asset's smallest unit. For extended compliance: max(0.4% of the amount, $0.45 equivalent); for basic: 0.4% with no floor.
	Fee string `json:"fee" url:"fee"`
	// Unique Suward identifier of the payment. Use it in the payment endpoints (get, cancel, transactions) and as the checkout page path.
	ID string `json:"id" url:"id"`
	// Arbitrary key/value data attached by the merchant at creation, echoed back unchanged.
	Metadata map[string]any `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Estimated on-chain (gas) cost, deducted from the received amount. Integer string in the asset's smallest unit.
	NetworkFee string `json:"networkFee" url:"networkFee"`
	// The service-fee rate applied to this payment, in basis points (e.g. 40 = 0.4%).
	ServiceFeeBps int `json:"serviceFeeBps" url:"serviceFeeBps"`
	// The minimum service-fee floor applied to this payment, as a USD decimal string (e.g. "0.45" for extended, "0" for basic).
	ServiceFeeMinUsd string `json:"serviceFeeMinUsd" url:"serviceFeeMinUsd"`
	// USD price of the asset locked at creation, decimal string. Fees are computed from this price at settlement, so the merchant's net is deterministic.
	QuotedPrice string `json:"quotedPrice" url:"quotedPrice"`
	// Who bears the network (gas) fee, echoed from creation.
	NetworkFeePayer CryptopayFeePayer `json:"networkFeePayer" url:"networkFeePayer"`
	// Who bears the platform (service) fee, echoed from creation.
	ServiceFeePayer CryptopayFeePayer `json:"serviceFeePayer" url:"serviceFeePayer"`
	// Resolved length of the payment window, in seconds.
	PaymentWindowSeconds int `json:"paymentWindowSeconds" url:"paymentWindowSeconds"`
	// Identifier of the project that owns this payment.
	ProjectID string `json:"projectId" url:"projectId"`
	// Return-to-store redirect configuration echoed from creation. Null when none was configured.
	RedirectConfig *CryptopayRedirectConfigDto `json:"redirectConfig,omitempty" url:"redirectConfig,omitempty"`
	// Main payment lifecycle status. See the status enum for the full meaning of each value.
	Status CryptopayPaymentStatusEnum `json:"status" url:"status"`
	// Fine-grained payment sub-status describing the current step or amount condition. See the sub-status enum for the full meaning of each value.
	SubStatus CryptopayPaymentSubStatusEnum `json:"subStatus" url:"subStatus"`
	// Preview page of the on-chain transactions detected for this payment (newest first). Use GET /v1/payments/{paymentId}/transactions for the full paginated list.
	Transactions *CryptopaywireTransactionList `json:"transactions" url:"transactions"`
	// Integer string in the asset's smallest unit.
	UnderpaymentTolerance *string `json:"underpaymentTolerance,omitempty" url:"underpaymentTolerance,omitempty"`
	// Unix-milliseconds timestamp when the payment was last updated.
	UpdatedAt int `json:"updatedAt" url:"updatedAt"`
	// Webhook URL that receives this payment's events, echoed from creation. Null when the project default webhook is used.
	WebhookURL *string `json:"webhookUrl,omitempty" url:"webhookUrl,omitempty"`
	// Absolute URL of the Suward-hosted checkout page where the customer pays this payment.
	PaymentPageURL string `json:"paymentPageUrl" url:"paymentPageUrl"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayPaymentResponse) GetAcceptedAt() *int {
	if c == nil {
		return nil
	}
	return c.AcceptedAt
}

func (c *CryptopayPaymentResponse) GetActivatedAt() *int {
	if c == nil {
		return nil
	}
	return c.ActivatedAt
}

func (c *CryptopayPaymentResponse) GetActivationFlowSeconds() *int {
	if c == nil {
		return nil
	}
	return c.ActivationFlowSeconds
}

func (c *CryptopayPaymentResponse) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CryptopayPaymentResponse) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CryptopayPaymentResponse) GetAmountConfirmed() string {
	if c == nil {
		return ""
	}
	return c.AmountConfirmed
}

func (c *CryptopayPaymentResponse) GetAmountReceived() string {
	if c == nil {
		return ""
	}
	return c.AmountReceived
}

func (c *CryptopayPaymentResponse) GetAsset() *CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.Asset
}

func (c *CryptopayPaymentResponse) GetConfirmedAt() *int {
	if c == nil {
		return nil
	}
	return c.ConfirmedAt
}

func (c *CryptopayPaymentResponse) GetCreatedAt() int {
	if c == nil {
		return 0
	}
	return c.CreatedAt
}

func (c *CryptopayPaymentResponse) GetExpiresAt() int {
	if c == nil {
		return 0
	}
	return c.ExpiresAt
}

func (c *CryptopayPaymentResponse) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CryptopayPaymentResponse) GetComplianceLevel() *CryptopayComplianceLevel {
	if c == nil {
		return nil
	}
	return c.ComplianceLevel
}

func (c *CryptopayPaymentResponse) GetFee() string {
	if c == nil {
		return ""
	}
	return c.Fee
}

func (c *CryptopayPaymentResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CryptopayPaymentResponse) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CryptopayPaymentResponse) GetNetworkFee() string {
	if c == nil {
		return ""
	}
	return c.NetworkFee
}

func (c *CryptopayPaymentResponse) GetServiceFeeBps() int {
	if c == nil {
		return 0
	}
	return c.ServiceFeeBps
}

func (c *CryptopayPaymentResponse) GetServiceFeeMinUsd() string {
	if c == nil {
		return ""
	}
	return c.ServiceFeeMinUsd
}

func (c *CryptopayPaymentResponse) GetQuotedPrice() string {
	if c == nil {
		return ""
	}
	return c.QuotedPrice
}

func (c *CryptopayPaymentResponse) GetNetworkFeePayer() CryptopayFeePayer {
	if c == nil {
		return ""
	}
	return c.NetworkFeePayer
}

func (c *CryptopayPaymentResponse) GetServiceFeePayer() CryptopayFeePayer {
	if c == nil {
		return ""
	}
	return c.ServiceFeePayer
}

func (c *CryptopayPaymentResponse) GetPaymentWindowSeconds() int {
	if c == nil {
		return 0
	}
	return c.PaymentWindowSeconds
}

func (c *CryptopayPaymentResponse) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CryptopayPaymentResponse) GetRedirectConfig() *CryptopayRedirectConfigDto {
	if c == nil {
		return nil
	}
	return c.RedirectConfig
}

func (c *CryptopayPaymentResponse) GetStatus() CryptopayPaymentStatusEnum {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CryptopayPaymentResponse) GetSubStatus() CryptopayPaymentSubStatusEnum {
	if c == nil {
		return ""
	}
	return c.SubStatus
}

func (c *CryptopayPaymentResponse) GetTransactions() *CryptopaywireTransactionList {
	if c == nil {
		return nil
	}
	return c.Transactions
}

func (c *CryptopayPaymentResponse) GetUnderpaymentTolerance() *string {
	if c == nil {
		return nil
	}
	return c.UnderpaymentTolerance
}

func (c *CryptopayPaymentResponse) GetUpdatedAt() int {
	if c == nil {
		return 0
	}
	return c.UpdatedAt
}

func (c *CryptopayPaymentResponse) GetWebhookURL() *string {
	if c == nil {
		return nil
	}
	return c.WebhookURL
}

func (c *CryptopayPaymentResponse) GetPaymentPageURL() string {
	if c == nil {
		return ""
	}
	return c.PaymentPageURL
}

func (c *CryptopayPaymentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayPaymentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAcceptedAt sets the AcceptedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAcceptedAt(acceptedAt *int) {
	c.AcceptedAt = acceptedAt
	c.require(cryptopayPaymentResponseFieldAcceptedAt)
}

// SetActivatedAt sets the ActivatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetActivatedAt(activatedAt *int) {
	c.ActivatedAt = activatedAt
	c.require(cryptopayPaymentResponseFieldActivatedAt)
}

// SetActivationFlowSeconds sets the ActivationFlowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetActivationFlowSeconds(activationFlowSeconds *int) {
	c.ActivationFlowSeconds = activationFlowSeconds
	c.require(cryptopayPaymentResponseFieldActivationFlowSeconds)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAddress(address *string) {
	c.Address = address
	c.require(cryptopayPaymentResponseFieldAddress)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAmount(amount string) {
	c.Amount = amount
	c.require(cryptopayPaymentResponseFieldAmount)
}

// SetAmountConfirmed sets the AmountConfirmed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAmountConfirmed(amountConfirmed string) {
	c.AmountConfirmed = amountConfirmed
	c.require(cryptopayPaymentResponseFieldAmountConfirmed)
}

// SetAmountReceived sets the AmountReceived field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAmountReceived(amountReceived string) {
	c.AmountReceived = amountReceived
	c.require(cryptopayPaymentResponseFieldAmountReceived)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayPaymentResponseFieldAsset)
}

// SetConfirmedAt sets the ConfirmedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetConfirmedAt(confirmedAt *int) {
	c.ConfirmedAt = confirmedAt
	c.require(cryptopayPaymentResponseFieldConfirmedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetCreatedAt(createdAt int) {
	c.CreatedAt = createdAt
	c.require(cryptopayPaymentResponseFieldCreatedAt)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetExpiresAt(expiresAt int) {
	c.ExpiresAt = expiresAt
	c.require(cryptopayPaymentResponseFieldExpiresAt)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(cryptopayPaymentResponseFieldExternalID)
}

// SetComplianceLevel sets the ComplianceLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetComplianceLevel(complianceLevel *CryptopayComplianceLevel) {
	c.ComplianceLevel = complianceLevel
	c.require(cryptopayPaymentResponseFieldComplianceLevel)
}

// SetFee sets the Fee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetFee(fee string) {
	c.Fee = fee
	c.require(cryptopayPaymentResponseFieldFee)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetID(id string) {
	c.ID = id
	c.require(cryptopayPaymentResponseFieldID)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(cryptopayPaymentResponseFieldMetadata)
}

// SetNetworkFee sets the NetworkFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetNetworkFee(networkFee string) {
	c.NetworkFee = networkFee
	c.require(cryptopayPaymentResponseFieldNetworkFee)
}

// SetServiceFeeBps sets the ServiceFeeBps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetServiceFeeBps(serviceFeeBps int) {
	c.ServiceFeeBps = serviceFeeBps
	c.require(cryptopayPaymentResponseFieldServiceFeeBps)
}

// SetServiceFeeMinUsd sets the ServiceFeeMinUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetServiceFeeMinUsd(serviceFeeMinUsd string) {
	c.ServiceFeeMinUsd = serviceFeeMinUsd
	c.require(cryptopayPaymentResponseFieldServiceFeeMinUsd)
}

// SetQuotedPrice sets the QuotedPrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetQuotedPrice(quotedPrice string) {
	c.QuotedPrice = quotedPrice
	c.require(cryptopayPaymentResponseFieldQuotedPrice)
}

// SetNetworkFeePayer sets the NetworkFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetNetworkFeePayer(networkFeePayer CryptopayFeePayer) {
	c.NetworkFeePayer = networkFeePayer
	c.require(cryptopayPaymentResponseFieldNetworkFeePayer)
}

// SetServiceFeePayer sets the ServiceFeePayer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetServiceFeePayer(serviceFeePayer CryptopayFeePayer) {
	c.ServiceFeePayer = serviceFeePayer
	c.require(cryptopayPaymentResponseFieldServiceFeePayer)
}

// SetPaymentWindowSeconds sets the PaymentWindowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetPaymentWindowSeconds(paymentWindowSeconds int) {
	c.PaymentWindowSeconds = paymentWindowSeconds
	c.require(cryptopayPaymentResponseFieldPaymentWindowSeconds)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetProjectID(projectID string) {
	c.ProjectID = projectID
	c.require(cryptopayPaymentResponseFieldProjectID)
}

// SetRedirectConfig sets the RedirectConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetRedirectConfig(redirectConfig *CryptopayRedirectConfigDto) {
	c.RedirectConfig = redirectConfig
	c.require(cryptopayPaymentResponseFieldRedirectConfig)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetStatus(status CryptopayPaymentStatusEnum) {
	c.Status = status
	c.require(cryptopayPaymentResponseFieldStatus)
}

// SetSubStatus sets the SubStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetSubStatus(subStatus CryptopayPaymentSubStatusEnum) {
	c.SubStatus = subStatus
	c.require(cryptopayPaymentResponseFieldSubStatus)
}

// SetTransactions sets the Transactions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetTransactions(transactions *CryptopaywireTransactionList) {
	c.Transactions = transactions
	c.require(cryptopayPaymentResponseFieldTransactions)
}

// SetUnderpaymentTolerance sets the UnderpaymentTolerance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetUnderpaymentTolerance(underpaymentTolerance *string) {
	c.UnderpaymentTolerance = underpaymentTolerance
	c.require(cryptopayPaymentResponseFieldUnderpaymentTolerance)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetUpdatedAt(updatedAt int) {
	c.UpdatedAt = updatedAt
	c.require(cryptopayPaymentResponseFieldUpdatedAt)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cryptopayPaymentResponseFieldWebhookURL)
}

// SetPaymentPageURL sets the PaymentPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPaymentResponse) SetPaymentPageURL(paymentPageURL string) {
	c.PaymentPageURL = paymentPageURL
	c.require(cryptopayPaymentResponseFieldPaymentPageURL)
}

func (c *CryptopayPaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayPaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayPaymentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayPaymentResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayPaymentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayPaymentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Terminal states: success (finalized), failed (terminal, no valid payment). Non-final: pending (awaiting funds), accepted (safe confirmations reached, credited — non-final until finalized).
type CryptopayPaymentStatusEnum string

const (
	CryptopayPaymentStatusEnumPending  CryptopayPaymentStatusEnum = "pending"
	CryptopayPaymentStatusEnumAccepted CryptopayPaymentStatusEnum = "accepted"
	CryptopayPaymentStatusEnumSuccess  CryptopayPaymentStatusEnum = "success"
	CryptopayPaymentStatusEnumFailed   CryptopayPaymentStatusEnum = "failed"
)

func NewCryptopayPaymentStatusEnumFromString(s string) (CryptopayPaymentStatusEnum, error) {
	switch s {
	case "pending":
		return CryptopayPaymentStatusEnumPending, nil
	case "accepted":
		return CryptopayPaymentStatusEnumAccepted, nil
	case "success":
		return CryptopayPaymentStatusEnumSuccess, nil
	case "failed":
		return CryptopayPaymentStatusEnumFailed, nil
	}
	var t CryptopayPaymentStatusEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayPaymentStatusEnum) Ptr() *CryptopayPaymentStatusEnum {
	return &c
}

// overpaid / underpaid: more or less than the requested amount was received. partiallyPaid: payment expired with a partial payment that never reached acceptance. complianceHold: held (under pending) for compliance review. complianceRejected: rejected by compliance (terminal, under failed).
type CryptopayPaymentSubStatusEnum string

const (
	CryptopayPaymentSubStatusEnumCreated            CryptopayPaymentSubStatusEnum = "created"
	CryptopayPaymentSubStatusEnumActivated          CryptopayPaymentSubStatusEnum = "activated"
	CryptopayPaymentSubStatusEnumAwaitingPayment    CryptopayPaymentSubStatusEnum = "awaitingPayment"
	CryptopayPaymentSubStatusEnumConfirming         CryptopayPaymentSubStatusEnum = "confirming"
	CryptopayPaymentSubStatusEnumCompleted          CryptopayPaymentSubStatusEnum = "completed"
	CryptopayPaymentSubStatusEnumOverpaid           CryptopayPaymentSubStatusEnum = "overpaid"
	CryptopayPaymentSubStatusEnumUnderpaid          CryptopayPaymentSubStatusEnum = "underpaid"
	CryptopayPaymentSubStatusEnumExpired            CryptopayPaymentSubStatusEnum = "expired"
	CryptopayPaymentSubStatusEnumCancelled          CryptopayPaymentSubStatusEnum = "cancelled"
	CryptopayPaymentSubStatusEnumPartiallyPaid      CryptopayPaymentSubStatusEnum = "partiallyPaid"
	CryptopayPaymentSubStatusEnumComplianceHold     CryptopayPaymentSubStatusEnum = "complianceHold"
	CryptopayPaymentSubStatusEnumComplianceRejected CryptopayPaymentSubStatusEnum = "complianceRejected"
)

func NewCryptopayPaymentSubStatusEnumFromString(s string) (CryptopayPaymentSubStatusEnum, error) {
	switch s {
	case "created":
		return CryptopayPaymentSubStatusEnumCreated, nil
	case "activated":
		return CryptopayPaymentSubStatusEnumActivated, nil
	case "awaitingPayment":
		return CryptopayPaymentSubStatusEnumAwaitingPayment, nil
	case "confirming":
		return CryptopayPaymentSubStatusEnumConfirming, nil
	case "completed":
		return CryptopayPaymentSubStatusEnumCompleted, nil
	case "overpaid":
		return CryptopayPaymentSubStatusEnumOverpaid, nil
	case "underpaid":
		return CryptopayPaymentSubStatusEnumUnderpaid, nil
	case "expired":
		return CryptopayPaymentSubStatusEnumExpired, nil
	case "cancelled":
		return CryptopayPaymentSubStatusEnumCancelled, nil
	case "partiallyPaid":
		return CryptopayPaymentSubStatusEnumPartiallyPaid, nil
	case "complianceHold":
		return CryptopayPaymentSubStatusEnumComplianceHold, nil
	case "complianceRejected":
		return CryptopayPaymentSubStatusEnumComplianceRejected, nil
	}
	var t CryptopayPaymentSubStatusEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayPaymentSubStatusEnum) Ptr() *CryptopayPaymentSubStatusEnum {
	return &c
}

var (
	cryptopayPublicPaymentResponseFieldActivatedAt           = big.NewInt(1 << 0)
	cryptopayPublicPaymentResponseFieldActivationFlowSeconds = big.NewInt(1 << 1)
	cryptopayPublicPaymentResponseFieldAddress               = big.NewInt(1 << 2)
	cryptopayPublicPaymentResponseFieldAmount                = big.NewInt(1 << 3)
	cryptopayPublicPaymentResponseFieldAmountReceived        = big.NewInt(1 << 4)
	cryptopayPublicPaymentResponseFieldAsset                 = big.NewInt(1 << 5)
	cryptopayPublicPaymentResponseFieldCreatedAt             = big.NewInt(1 << 6)
	cryptopayPublicPaymentResponseFieldExpiresAt             = big.NewInt(1 << 7)
	cryptopayPublicPaymentResponseFieldID                    = big.NewInt(1 << 8)
	cryptopayPublicPaymentResponseFieldPaymentWindowSeconds  = big.NewInt(1 << 9)
	cryptopayPublicPaymentResponseFieldRedirect              = big.NewInt(1 << 10)
	cryptopayPublicPaymentResponseFieldStatus                = big.NewInt(1 << 11)
	cryptopayPublicPaymentResponseFieldSubStatus             = big.NewInt(1 << 12)
	cryptopayPublicPaymentResponseFieldUnderpaymentTolerance = big.NewInt(1 << 13)
	cryptopayPublicPaymentResponseFieldUpdatedAt             = big.NewInt(1 << 14)
	cryptopayPublicPaymentResponseFieldPaymentPageURL        = big.NewInt(1 << 15)
)

type CryptopayPublicPaymentResponse struct {
	// Unix-milliseconds timestamp when the payment was activated. Null before activation.
	ActivatedAt *int `json:"activatedAt,omitempty" url:"activatedAt,omitempty"`
	// Activation grace period in seconds before the payment window starts counting. Null when not configured.
	ActivationFlowSeconds *int `json:"activationFlowSeconds,omitempty" url:"activationFlowSeconds,omitempty"`
	// On-chain deposit address the customer must send funds to. Null until the payment is activated and an address is assigned.
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Integer string in the asset's smallest unit.
	Amount string `json:"amount" url:"amount"`
	// Integer string in the asset's smallest unit.
	AmountReceived string `json:"amountReceived" url:"amountReceived"`
	// Asset the payment is denominated in, as an asset id-string (see GET /v1/assets). Null until an asset is selected.
	Asset *CryptopayAssetID `json:"asset,omitempty" url:"asset,omitempty"`
	// Unix-milliseconds timestamp when the payment was created.
	CreatedAt int `json:"createdAt" url:"createdAt"`
	// Unix-milliseconds timestamp when the payment window closes; the payment expires if unpaid by then.
	ExpiresAt int `json:"expiresAt" url:"expiresAt"`
	// Unique Suward identifier of the payment.
	ID string `json:"id" url:"id"`
	// Length of the payment window in seconds — how long the payment stays open for funding once activated.
	PaymentWindowSeconds int `json:"paymentWindowSeconds" url:"paymentWindowSeconds"`
	// Resolved "return to store" redirect (base URL plus the query parameters to append) used to send the customer back after payment. Null when none was configured.
	Redirect *CryptopayPublicRedirect `json:"redirect,omitempty" url:"redirect,omitempty"`
	// Main payment lifecycle status. See the status enum for the full meaning of each value.
	Status CryptopayPaymentStatusEnum `json:"status" url:"status"`
	// Fine-grained payment sub-status. See the sub-status enum for the full meaning of each value.
	SubStatus CryptopayPaymentSubStatusEnum `json:"subStatus" url:"subStatus"`
	// Integer string in the asset's smallest unit.
	UnderpaymentTolerance *string `json:"underpaymentTolerance,omitempty" url:"underpaymentTolerance,omitempty"`
	// Unix-milliseconds timestamp when the payment was last updated.
	UpdatedAt int `json:"updatedAt" url:"updatedAt"`
	// Absolute URL of the Suward-hosted checkout page where the customer pays this payment.
	PaymentPageURL string `json:"paymentPageUrl" url:"paymentPageUrl"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayPublicPaymentResponse) GetActivatedAt() *int {
	if c == nil {
		return nil
	}
	return c.ActivatedAt
}

func (c *CryptopayPublicPaymentResponse) GetActivationFlowSeconds() *int {
	if c == nil {
		return nil
	}
	return c.ActivationFlowSeconds
}

func (c *CryptopayPublicPaymentResponse) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CryptopayPublicPaymentResponse) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CryptopayPublicPaymentResponse) GetAmountReceived() string {
	if c == nil {
		return ""
	}
	return c.AmountReceived
}

func (c *CryptopayPublicPaymentResponse) GetAsset() *CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.Asset
}

func (c *CryptopayPublicPaymentResponse) GetCreatedAt() int {
	if c == nil {
		return 0
	}
	return c.CreatedAt
}

func (c *CryptopayPublicPaymentResponse) GetExpiresAt() int {
	if c == nil {
		return 0
	}
	return c.ExpiresAt
}

func (c *CryptopayPublicPaymentResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CryptopayPublicPaymentResponse) GetPaymentWindowSeconds() int {
	if c == nil {
		return 0
	}
	return c.PaymentWindowSeconds
}

func (c *CryptopayPublicPaymentResponse) GetRedirect() *CryptopayPublicRedirect {
	if c == nil {
		return nil
	}
	return c.Redirect
}

func (c *CryptopayPublicPaymentResponse) GetStatus() CryptopayPaymentStatusEnum {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CryptopayPublicPaymentResponse) GetSubStatus() CryptopayPaymentSubStatusEnum {
	if c == nil {
		return ""
	}
	return c.SubStatus
}

func (c *CryptopayPublicPaymentResponse) GetUnderpaymentTolerance() *string {
	if c == nil {
		return nil
	}
	return c.UnderpaymentTolerance
}

func (c *CryptopayPublicPaymentResponse) GetUpdatedAt() int {
	if c == nil {
		return 0
	}
	return c.UpdatedAt
}

func (c *CryptopayPublicPaymentResponse) GetPaymentPageURL() string {
	if c == nil {
		return ""
	}
	return c.PaymentPageURL
}

func (c *CryptopayPublicPaymentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayPublicPaymentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActivatedAt sets the ActivatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetActivatedAt(activatedAt *int) {
	c.ActivatedAt = activatedAt
	c.require(cryptopayPublicPaymentResponseFieldActivatedAt)
}

// SetActivationFlowSeconds sets the ActivationFlowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetActivationFlowSeconds(activationFlowSeconds *int) {
	c.ActivationFlowSeconds = activationFlowSeconds
	c.require(cryptopayPublicPaymentResponseFieldActivationFlowSeconds)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAddress(address *string) {
	c.Address = address
	c.require(cryptopayPublicPaymentResponseFieldAddress)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAmount(amount string) {
	c.Amount = amount
	c.require(cryptopayPublicPaymentResponseFieldAmount)
}

// SetAmountReceived sets the AmountReceived field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAmountReceived(amountReceived string) {
	c.AmountReceived = amountReceived
	c.require(cryptopayPublicPaymentResponseFieldAmountReceived)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayPublicPaymentResponseFieldAsset)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetCreatedAt(createdAt int) {
	c.CreatedAt = createdAt
	c.require(cryptopayPublicPaymentResponseFieldCreatedAt)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetExpiresAt(expiresAt int) {
	c.ExpiresAt = expiresAt
	c.require(cryptopayPublicPaymentResponseFieldExpiresAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetID(id string) {
	c.ID = id
	c.require(cryptopayPublicPaymentResponseFieldID)
}

// SetPaymentWindowSeconds sets the PaymentWindowSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetPaymentWindowSeconds(paymentWindowSeconds int) {
	c.PaymentWindowSeconds = paymentWindowSeconds
	c.require(cryptopayPublicPaymentResponseFieldPaymentWindowSeconds)
}

// SetRedirect sets the Redirect field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetRedirect(redirect *CryptopayPublicRedirect) {
	c.Redirect = redirect
	c.require(cryptopayPublicPaymentResponseFieldRedirect)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetStatus(status CryptopayPaymentStatusEnum) {
	c.Status = status
	c.require(cryptopayPublicPaymentResponseFieldStatus)
}

// SetSubStatus sets the SubStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetSubStatus(subStatus CryptopayPaymentSubStatusEnum) {
	c.SubStatus = subStatus
	c.require(cryptopayPublicPaymentResponseFieldSubStatus)
}

// SetUnderpaymentTolerance sets the UnderpaymentTolerance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetUnderpaymentTolerance(underpaymentTolerance *string) {
	c.UnderpaymentTolerance = underpaymentTolerance
	c.require(cryptopayPublicPaymentResponseFieldUnderpaymentTolerance)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetUpdatedAt(updatedAt int) {
	c.UpdatedAt = updatedAt
	c.require(cryptopayPublicPaymentResponseFieldUpdatedAt)
}

// SetPaymentPageURL sets the PaymentPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicPaymentResponse) SetPaymentPageURL(paymentPageURL string) {
	c.PaymentPageURL = paymentPageURL
	c.require(cryptopayPublicPaymentResponseFieldPaymentPageURL)
}

func (c *CryptopayPublicPaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayPublicPaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayPublicPaymentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayPublicPaymentResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayPublicPaymentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayPublicPaymentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayPublicRedirectFieldQuery = big.NewInt(1 << 0)
	cryptopayPublicRedirectFieldURL   = big.NewInt(1 << 1)
)

type CryptopayPublicRedirect struct {
	// Query parameters to append to the URL when redirecting the customer back, e.g. id, externalId, data. Empty when the redirect has no parameters.
	Query map[string]string `json:"query" url:"query"`
	// Base "return to store" URL the customer is sent back to after paying.
	URL string `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayPublicRedirect) GetQuery() map[string]string {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *CryptopayPublicRedirect) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *CryptopayPublicRedirect) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayPublicRedirect) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicRedirect) SetQuery(query map[string]string) {
	c.Query = query
	c.require(cryptopayPublicRedirectFieldQuery)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayPublicRedirect) SetURL(url string) {
	c.URL = url
	c.require(cryptopayPublicRedirectFieldURL)
}

func (c *CryptopayPublicRedirect) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayPublicRedirect
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayPublicRedirect(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayPublicRedirect) MarshalJSON() ([]byte, error) {
	type embed CryptopayPublicRedirect
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayPublicRedirect) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayQuotePaymentResponseFieldAsset           = big.NewInt(1 << 0)
	cryptopayQuotePaymentResponseFieldAmount          = big.NewInt(1 << 1)
	cryptopayQuotePaymentResponseFieldFee             = big.NewInt(1 << 2)
	cryptopayQuotePaymentResponseFieldComplianceLevel = big.NewInt(1 << 3)
	cryptopayQuotePaymentResponseFieldNetworkFee      = big.NewInt(1 << 4)
	cryptopayQuotePaymentResponseFieldNetAmount       = big.NewInt(1 << 5)
	cryptopayQuotePaymentResponseFieldGross           = big.NewInt(1 << 6)
	cryptopayQuotePaymentResponseFieldQuotedPrice     = big.NewInt(1 << 7)
)

type CryptopayQuotePaymentResponse struct {
	// Asset the quote is denominated in, echoed from the request.
	Asset CryptopayAssetID `json:"asset" url:"asset"`
	// Gross amount, integer string in the asset's smallest unit.
	Amount string `json:"amount" url:"amount"`
	// Platform fee, integer string in the asset's smallest unit. For extended compliance: max(0.4% of the amount, $0.45 equivalent); for basic: 0.4% with no floor.
	Fee string `json:"fee" url:"fee"`
	// AML screening depth used for this quote: basic or extended.
	ComplianceLevel *CryptopayComplianceLevel `json:"complianceLevel,omitempty" url:"complianceLevel,omitempty"`
	// Estimated on-chain (gas) cost, deducted from the received amount. Integer string in the asset's smallest unit.
	NetworkFee string `json:"networkFee" url:"networkFee"`
	// Amount the merchant receives after all fees. Integer string in the asset's smallest unit.
	NetAmount string `json:"netAmount" url:"netAmount"`
	// Amount the customer pays: base plus any customer-paid fees. Integer string in the asset's smallest unit.
	Gross string `json:"gross" url:"gross"`
	// USD price used for this quote, decimal string. Not locked — the binding price is captured when the payment is created.
	QuotedPrice string `json:"quotedPrice" url:"quotedPrice"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayQuotePaymentResponse) GetAsset() CryptopayAssetID {
	if c == nil {
		return ""
	}
	return c.Asset
}

func (c *CryptopayQuotePaymentResponse) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CryptopayQuotePaymentResponse) GetFee() string {
	if c == nil {
		return ""
	}
	return c.Fee
}

func (c *CryptopayQuotePaymentResponse) GetComplianceLevel() *CryptopayComplianceLevel {
	if c == nil {
		return nil
	}
	return c.ComplianceLevel
}

func (c *CryptopayQuotePaymentResponse) GetNetworkFee() string {
	if c == nil {
		return ""
	}
	return c.NetworkFee
}

func (c *CryptopayQuotePaymentResponse) GetNetAmount() string {
	if c == nil {
		return ""
	}
	return c.NetAmount
}

func (c *CryptopayQuotePaymentResponse) GetGross() string {
	if c == nil {
		return ""
	}
	return c.Gross
}

func (c *CryptopayQuotePaymentResponse) GetQuotedPrice() string {
	if c == nil {
		return ""
	}
	return c.QuotedPrice
}

func (c *CryptopayQuotePaymentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayQuotePaymentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetAsset(asset CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayQuotePaymentResponseFieldAsset)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetAmount(amount string) {
	c.Amount = amount
	c.require(cryptopayQuotePaymentResponseFieldAmount)
}

// SetFee sets the Fee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetFee(fee string) {
	c.Fee = fee
	c.require(cryptopayQuotePaymentResponseFieldFee)
}

// SetComplianceLevel sets the ComplianceLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetComplianceLevel(complianceLevel *CryptopayComplianceLevel) {
	c.ComplianceLevel = complianceLevel
	c.require(cryptopayQuotePaymentResponseFieldComplianceLevel)
}

// SetNetworkFee sets the NetworkFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetNetworkFee(networkFee string) {
	c.NetworkFee = networkFee
	c.require(cryptopayQuotePaymentResponseFieldNetworkFee)
}

// SetNetAmount sets the NetAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetNetAmount(netAmount string) {
	c.NetAmount = netAmount
	c.require(cryptopayQuotePaymentResponseFieldNetAmount)
}

// SetGross sets the Gross field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetGross(gross string) {
	c.Gross = gross
	c.require(cryptopayQuotePaymentResponseFieldGross)
}

// SetQuotedPrice sets the QuotedPrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayQuotePaymentResponse) SetQuotedPrice(quotedPrice string) {
	c.QuotedPrice = quotedPrice
	c.require(cryptopayQuotePaymentResponseFieldQuotedPrice)
}

func (c *CryptopayQuotePaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayQuotePaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayQuotePaymentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayQuotePaymentResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayQuotePaymentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayQuotePaymentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayRedirectConfigDtoFieldData   = big.NewInt(1 << 0)
	cryptopayRedirectConfigDtoFieldParams = big.NewInt(1 << 1)
	cryptopayRedirectConfigDtoFieldURL    = big.NewInt(1 << 2)
)

type CryptopayRedirectConfigDto struct {
	// Opaque string passed through unchanged as the "data" query parameter on the return URL. Use it to carry your own session/order token.
	Data *string `json:"data,omitempty" url:"data,omitempty"`
	// Which payment identifiers to append to the return URL as query parameters. Allowed values: "id" (the Suward payment id) and "externalId" (your identifier).
	Params []CryptopayRedirectConfigDtoParamsItem `json:"params,omitempty" url:"params,omitempty"`
	// Base "return to store" URL the customer is sent back to after paying.
	URL string `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayRedirectConfigDto) GetData() *string {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CryptopayRedirectConfigDto) GetParams() []CryptopayRedirectConfigDtoParamsItem {
	if c == nil {
		return nil
	}
	return c.Params
}

func (c *CryptopayRedirectConfigDto) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *CryptopayRedirectConfigDto) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayRedirectConfigDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayRedirectConfigDto) SetData(data *string) {
	c.Data = data
	c.require(cryptopayRedirectConfigDtoFieldData)
}

// SetParams sets the Params field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayRedirectConfigDto) SetParams(params []CryptopayRedirectConfigDtoParamsItem) {
	c.Params = params
	c.require(cryptopayRedirectConfigDtoFieldParams)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayRedirectConfigDto) SetURL(url string) {
	c.URL = url
	c.require(cryptopayRedirectConfigDtoFieldURL)
}

func (c *CryptopayRedirectConfigDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayRedirectConfigDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayRedirectConfigDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayRedirectConfigDto) MarshalJSON() ([]byte, error) {
	type embed CryptopayRedirectConfigDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayRedirectConfigDto) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CryptopayRedirectConfigDtoParamsItem string

const (
	CryptopayRedirectConfigDtoParamsItemID         CryptopayRedirectConfigDtoParamsItem = "id"
	CryptopayRedirectConfigDtoParamsItemExternalID CryptopayRedirectConfigDtoParamsItem = "externalId"
)

func NewCryptopayRedirectConfigDtoParamsItemFromString(s string) (CryptopayRedirectConfigDtoParamsItem, error) {
	switch s {
	case "id":
		return CryptopayRedirectConfigDtoParamsItemID, nil
	case "externalId":
		return CryptopayRedirectConfigDtoParamsItemExternalID, nil
	}
	var t CryptopayRedirectConfigDtoParamsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayRedirectConfigDtoParamsItem) Ptr() *CryptopayRedirectConfigDtoParamsItem {
	return &c
}

var (
	cryptopayTransactionResponseFieldAcceptedAt = big.NewInt(1 << 0)
	cryptopayTransactionResponseFieldAmount     = big.NewInt(1 << 1)
	cryptopayTransactionResponseFieldDetectedAt = big.NewInt(1 << 2)
	cryptopayTransactionResponseFieldTxHash     = big.NewInt(1 << 3)
)

type CryptopayTransactionResponse struct {
	// Unix-milliseconds timestamp when the transfer reached the accepted (safe) confirmation tier. Null before acceptance.
	AcceptedAt *int `json:"acceptedAt,omitempty" url:"acceptedAt,omitempty"`
	// On-chain transfer amount, an integer string in the asset's smallest unit (see CreatePaymentRequest.amount).
	Amount string `json:"amount" url:"amount"`
	// Unix-milliseconds timestamp when the transfer was first seen on-chain.
	DetectedAt int `json:"detectedAt" url:"detectedAt"`
	// On-chain transaction hash of the transfer.
	TxHash string `json:"txHash" url:"txHash"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayTransactionResponse) GetAcceptedAt() *int {
	if c == nil {
		return nil
	}
	return c.AcceptedAt
}

func (c *CryptopayTransactionResponse) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CryptopayTransactionResponse) GetDetectedAt() int {
	if c == nil {
		return 0
	}
	return c.DetectedAt
}

func (c *CryptopayTransactionResponse) GetTxHash() string {
	if c == nil {
		return ""
	}
	return c.TxHash
}

func (c *CryptopayTransactionResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayTransactionResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAcceptedAt sets the AcceptedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetAcceptedAt(acceptedAt *int) {
	c.AcceptedAt = acceptedAt
	c.require(cryptopayTransactionResponseFieldAcceptedAt)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetAmount(amount string) {
	c.Amount = amount
	c.require(cryptopayTransactionResponseFieldAmount)
}

// SetDetectedAt sets the DetectedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetDetectedAt(detectedAt int) {
	c.DetectedAt = detectedAt
	c.require(cryptopayTransactionResponseFieldDetectedAt)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayTransactionResponse) SetTxHash(txHash string) {
	c.TxHash = txHash
	c.require(cryptopayTransactionResponseFieldTxHash)
}

func (c *CryptopayTransactionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayTransactionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayTransactionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayTransactionResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayTransactionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayTransactionResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopaywireTransactionListFieldHasMore = big.NewInt(1 << 0)
	cryptopaywireTransactionListFieldItems   = big.NewInt(1 << 1)
)

type CryptopaywireTransactionList struct {
	// True when more transactions exist beyond this page. To fetch the next page, pass the last item's id as the lastId query parameter.
	HasMore bool `json:"hasMore" url:"hasMore"`
	// Page of transactions, ordered per the request's order parameter.
	Items []*CryptopayTransactionResponse `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopaywireTransactionList) GetHasMore() bool {
	if c == nil {
		return false
	}
	return c.HasMore
}

func (c *CryptopaywireTransactionList) GetItems() []*CryptopayTransactionResponse {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CryptopaywireTransactionList) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopaywireTransactionList) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaywireTransactionList) SetHasMore(hasMore bool) {
	c.HasMore = hasMore
	c.require(cryptopaywireTransactionListFieldHasMore)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaywireTransactionList) SetItems(items []*CryptopayTransactionResponse) {
	c.Items = items
	c.require(cryptopaywireTransactionListFieldItems)
}

func (c *CryptopaywireTransactionList) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopaywireTransactionList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopaywireTransactionList(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopaywireTransactionList) MarshalJSON() ([]byte, error) {
	type embed CryptopaywireTransactionList
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopaywireTransactionList) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type GetV1PaymentsPaymentIDResponse struct {
	CryptopayPaymentResponse       *CryptopayPaymentResponse
	CryptopayPublicPaymentResponse *CryptopayPublicPaymentResponse

	typ string
}

func (g *GetV1PaymentsPaymentIDResponse) GetCryptopayPaymentResponse() *CryptopayPaymentResponse {
	if g == nil {
		return nil
	}
	return g.CryptopayPaymentResponse
}

func (g *GetV1PaymentsPaymentIDResponse) GetCryptopayPublicPaymentResponse() *CryptopayPublicPaymentResponse {
	if g == nil {
		return nil
	}
	return g.CryptopayPublicPaymentResponse
}

func (g *GetV1PaymentsPaymentIDResponse) UnmarshalJSON(data []byte) error {
	valueCryptopayPaymentResponse := new(CryptopayPaymentResponse)
	if err := json.Unmarshal(data, &valueCryptopayPaymentResponse); err == nil {
		g.typ = "CryptopayPaymentResponse"
		g.CryptopayPaymentResponse = valueCryptopayPaymentResponse
		return nil
	}
	valueCryptopayPublicPaymentResponse := new(CryptopayPublicPaymentResponse)
	if err := json.Unmarshal(data, &valueCryptopayPublicPaymentResponse); err == nil {
		g.typ = "CryptopayPublicPaymentResponse"
		g.CryptopayPublicPaymentResponse = valueCryptopayPublicPaymentResponse
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetV1PaymentsPaymentIDResponse) MarshalJSON() ([]byte, error) {
	if g.typ == "CryptopayPaymentResponse" || g.CryptopayPaymentResponse != nil {
		return json.Marshal(g.CryptopayPaymentResponse)
	}
	if g.typ == "CryptopayPublicPaymentResponse" || g.CryptopayPublicPaymentResponse != nil {
		return json.Marshal(g.CryptopayPublicPaymentResponse)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetV1PaymentsPaymentIDResponseVisitor interface {
	VisitCryptopayPaymentResponse(*CryptopayPaymentResponse) error
	VisitCryptopayPublicPaymentResponse(*CryptopayPublicPaymentResponse) error
}

func (g *GetV1PaymentsPaymentIDResponse) Accept(visitor GetV1PaymentsPaymentIDResponseVisitor) error {
	if g.typ == "CryptopayPaymentResponse" || g.CryptopayPaymentResponse != nil {
		return visitor.VisitCryptopayPaymentResponse(g.CryptopayPaymentResponse)
	}
	if g.typ == "CryptopayPublicPaymentResponse" || g.CryptopayPublicPaymentResponse != nil {
		return visitor.VisitCryptopayPublicPaymentResponse(g.CryptopayPublicPaymentResponse)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetV1PaymentsPaymentIDTransactionsRequestOrder string

const (
	GetV1PaymentsPaymentIDTransactionsRequestOrderAsc  GetV1PaymentsPaymentIDTransactionsRequestOrder = "asc"
	GetV1PaymentsPaymentIDTransactionsRequestOrderDesc GetV1PaymentsPaymentIDTransactionsRequestOrder = "desc"
)

func NewGetV1PaymentsPaymentIDTransactionsRequestOrderFromString(s string) (GetV1PaymentsPaymentIDTransactionsRequestOrder, error) {
	switch s {
	case "asc":
		return GetV1PaymentsPaymentIDTransactionsRequestOrderAsc, nil
	case "desc":
		return GetV1PaymentsPaymentIDTransactionsRequestOrderDesc, nil
	}
	var t GetV1PaymentsPaymentIDTransactionsRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetV1PaymentsPaymentIDTransactionsRequestOrder) Ptr() *GetV1PaymentsPaymentIDTransactionsRequestOrder {
	return &g
}

type GetV1PaymentsRequestOrder string

const (
	GetV1PaymentsRequestOrderAsc  GetV1PaymentsRequestOrder = "asc"
	GetV1PaymentsRequestOrderDesc GetV1PaymentsRequestOrder = "desc"
)

func NewGetV1PaymentsRequestOrderFromString(s string) (GetV1PaymentsRequestOrder, error) {
	switch s {
	case "asc":
		return GetV1PaymentsRequestOrderAsc, nil
	case "desc":
		return GetV1PaymentsRequestOrderDesc, nil
	}
	var t GetV1PaymentsRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetV1PaymentsRequestOrder) Ptr() *GetV1PaymentsRequestOrder {
	return &g
}
