// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	big "math/big"
)

var (
	cryptopayCreateStaticWalletRequestFieldAllowedAssets = big.NewInt(1 << 0)
	cryptopayCreateStaticWalletRequestFieldExternalID    = big.NewInt(1 << 1)
	cryptopayCreateStaticWalletRequestFieldIsTest        = big.NewInt(1 << 2)
	cryptopayCreateStaticWalletRequestFieldMetadata      = big.NewInt(1 << 3)
	cryptopayCreateStaticWalletRequestFieldWebhookURL    = big.NewInt(1 << 4)
)

type CryptopayCreateStaticWalletRequest struct {
	AllowedAssets []CryptopayAssetID `json:"allowedAssets,omitempty" url:"-"`
	ExternalID    *string            `json:"externalId,omitempty" url:"-"`
	IsTest        *bool              `json:"isTest,omitempty" url:"-"`
	Metadata      map[string]any     `json:"metadata,omitempty" url:"-"`
	WebhookURL    *string            `json:"webhookUrl,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopayCreateStaticWalletRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAllowedAssets sets the AllowedAssets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreateStaticWalletRequest) SetAllowedAssets(allowedAssets []CryptopayAssetID) {
	c.AllowedAssets = allowedAssets
	c.require(cryptopayCreateStaticWalletRequestFieldAllowedAssets)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreateStaticWalletRequest) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(cryptopayCreateStaticWalletRequestFieldExternalID)
}

// SetIsTest sets the IsTest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreateStaticWalletRequest) SetIsTest(isTest *bool) {
	c.IsTest = isTest
	c.require(cryptopayCreateStaticWalletRequestFieldIsTest)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreateStaticWalletRequest) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(cryptopayCreateStaticWalletRequestFieldMetadata)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayCreateStaticWalletRequest) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cryptopayCreateStaticWalletRequestFieldWebhookURL)
}

func (c *CryptopayCreateStaticWalletRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayCreateStaticWalletRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopayCreateStaticWalletRequest(body)
	return nil
}

func (c *CryptopayCreateStaticWalletRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopayCreateStaticWalletRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteV1StaticWalletsStaticWalletIDRequestFieldStaticWalletID = big.NewInt(1 << 0)
)

type DeleteV1StaticWalletsStaticWalletIDRequest struct {
	// Static wallet ID
	StaticWalletID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteV1StaticWalletsStaticWalletIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetStaticWalletID sets the StaticWalletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteV1StaticWalletsStaticWalletIDRequest) SetStaticWalletID(staticWalletID string) {
	d.StaticWalletID = staticWalletID
	d.require(deleteV1StaticWalletsStaticWalletIDRequestFieldStaticWalletID)
}

var (
	getV1StaticWalletsStaticWalletIDRequestFieldStaticWalletID = big.NewInt(1 << 0)
)

type GetV1StaticWalletsStaticWalletIDRequest struct {
	// Static wallet ID
	StaticWalletID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1StaticWalletsStaticWalletIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetStaticWalletID sets the StaticWalletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsStaticWalletIDRequest) SetStaticWalletID(staticWalletID string) {
	g.StaticWalletID = staticWalletID
	g.require(getV1StaticWalletsStaticWalletIDRequestFieldStaticWalletID)
}

var (
	getV1StaticWalletsStaticWalletIDDepositsDepositIDRequestFieldStaticWalletID = big.NewInt(1 << 0)
	getV1StaticWalletsStaticWalletIDDepositsDepositIDRequestFieldDepositID      = big.NewInt(1 << 1)
)

type GetV1StaticWalletsStaticWalletIDDepositsDepositIDRequest struct {
	// Static wallet ID
	StaticWalletID string `json:"-" url:"-"`
	// Deposit ID
	DepositID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1StaticWalletsStaticWalletIDDepositsDepositIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetStaticWalletID sets the StaticWalletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsStaticWalletIDDepositsDepositIDRequest) SetStaticWalletID(staticWalletID string) {
	g.StaticWalletID = staticWalletID
	g.require(getV1StaticWalletsStaticWalletIDDepositsDepositIDRequestFieldStaticWalletID)
}

// SetDepositID sets the DepositID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsStaticWalletIDDepositsDepositIDRequest) SetDepositID(depositID string) {
	g.DepositID = depositID
	g.require(getV1StaticWalletsStaticWalletIDDepositsDepositIDRequestFieldDepositID)
}

var (
	getV1StaticWalletsStaticWalletIDDepositsRequestFieldStaticWalletID = big.NewInt(1 << 0)
	getV1StaticWalletsStaticWalletIDDepositsRequestFieldOrder          = big.NewInt(1 << 1)
	getV1StaticWalletsStaticWalletIDDepositsRequestFieldLimit          = big.NewInt(1 << 2)
	getV1StaticWalletsStaticWalletIDDepositsRequestFieldLastID         = big.NewInt(1 << 3)
)

type GetV1StaticWalletsStaticWalletIDDepositsRequest struct {
	// Static wallet ID
	StaticWalletID string `json:"-" url:"-"`
	// Sort order (asc/desc)
	Order *GetV1StaticWalletsStaticWalletIDDepositsRequestOrder `json:"-" url:"order,omitempty"`
	// Limit (default 20, max 100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Last ID for pagination
	LastID *string `json:"-" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1StaticWalletsStaticWalletIDDepositsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetStaticWalletID sets the StaticWalletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsStaticWalletIDDepositsRequest) SetStaticWalletID(staticWalletID string) {
	g.StaticWalletID = staticWalletID
	g.require(getV1StaticWalletsStaticWalletIDDepositsRequestFieldStaticWalletID)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsStaticWalletIDDepositsRequest) SetOrder(order *GetV1StaticWalletsStaticWalletIDDepositsRequestOrder) {
	g.Order = order
	g.require(getV1StaticWalletsStaticWalletIDDepositsRequestFieldOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsStaticWalletIDDepositsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getV1StaticWalletsStaticWalletIDDepositsRequestFieldLimit)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsStaticWalletIDDepositsRequest) SetLastID(lastID *string) {
	g.LastID = lastID
	g.require(getV1StaticWalletsStaticWalletIDDepositsRequestFieldLastID)
}

var (
	getV1StaticWalletsRequestFieldOrder  = big.NewInt(1 << 0)
	getV1StaticWalletsRequestFieldLimit  = big.NewInt(1 << 1)
	getV1StaticWalletsRequestFieldLastID = big.NewInt(1 << 2)
)

type GetV1StaticWalletsRequest struct {
	// Sort order (asc/desc)
	Order *GetV1StaticWalletsRequestOrder `json:"-" url:"order,omitempty"`
	// Limit (default 20, max 100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Last ID for pagination
	LastID *string `json:"-" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetV1StaticWalletsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsRequest) SetOrder(order *GetV1StaticWalletsRequestOrder) {
	g.Order = order
	g.require(getV1StaticWalletsRequestFieldOrder)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getV1StaticWalletsRequestFieldLimit)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetV1StaticWalletsRequest) SetLastID(lastID *string) {
	g.LastID = lastID
	g.require(getV1StaticWalletsRequestFieldLastID)
}

var (
	cryptopaySimulateStaticDepositRequestFieldStaticWalletID = big.NewInt(1 << 0)
	cryptopaySimulateStaticDepositRequestFieldAmount         = big.NewInt(1 << 1)
	cryptopaySimulateStaticDepositRequestFieldAsset          = big.NewInt(1 << 2)
	cryptopaySimulateStaticDepositRequestFieldStatus         = big.NewInt(1 << 3)
	cryptopaySimulateStaticDepositRequestFieldTransferIndex  = big.NewInt(1 << 4)
	cryptopaySimulateStaticDepositRequestFieldTxHash         = big.NewInt(1 << 5)
)

type CryptopaySimulateStaticDepositRequest struct {
	// Static wallet ID
	StaticWalletID string                                       `json:"-" url:"-"`
	Amount         *string                                      `json:"amount,omitempty" url:"-"`
	Asset          *CryptopayAssetID                            `json:"asset,omitempty" url:"-"`
	Status         *CryptopaySimulateStaticDepositRequestStatus `json:"status,omitempty" url:"-"`
	TransferIndex  *string                                      `json:"transferIndex,omitempty" url:"-"`
	TxHash         *string                                      `json:"txHash,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopaySimulateStaticDepositRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetStaticWalletID sets the StaticWalletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulateStaticDepositRequest) SetStaticWalletID(staticWalletID string) {
	c.StaticWalletID = staticWalletID
	c.require(cryptopaySimulateStaticDepositRequestFieldStaticWalletID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulateStaticDepositRequest) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopaySimulateStaticDepositRequestFieldAmount)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulateStaticDepositRequest) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopaySimulateStaticDepositRequestFieldAsset)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulateStaticDepositRequest) SetStatus(status *CryptopaySimulateStaticDepositRequestStatus) {
	c.Status = status
	c.require(cryptopaySimulateStaticDepositRequestFieldStatus)
}

// SetTransferIndex sets the TransferIndex field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulateStaticDepositRequest) SetTransferIndex(transferIndex *string) {
	c.TransferIndex = transferIndex
	c.require(cryptopaySimulateStaticDepositRequestFieldTransferIndex)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopaySimulateStaticDepositRequest) SetTxHash(txHash *string) {
	c.TxHash = txHash
	c.require(cryptopaySimulateStaticDepositRequestFieldTxHash)
}

func (c *CryptopaySimulateStaticDepositRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopaySimulateStaticDepositRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopaySimulateStaticDepositRequest(body)
	return nil
}

func (c *CryptopaySimulateStaticDepositRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopaySimulateStaticDepositRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	cryptopayListStaticDepositsResponseFieldHasMore = big.NewInt(1 << 0)
	cryptopayListStaticDepositsResponseFieldItems   = big.NewInt(1 << 1)
	cryptopayListStaticDepositsResponseFieldLastID  = big.NewInt(1 << 2)
)

type CryptopayListStaticDepositsResponse struct {
	HasMore *bool                             `json:"hasMore,omitempty" url:"hasMore,omitempty"`
	Items   []*CryptopayStaticDepositResponse `json:"items,omitempty" url:"items,omitempty"`
	LastID  *string                           `json:"lastId,omitempty" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayListStaticDepositsResponse) GetHasMore() *bool {
	if c == nil {
		return nil
	}
	return c.HasMore
}

func (c *CryptopayListStaticDepositsResponse) GetItems() []*CryptopayStaticDepositResponse {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CryptopayListStaticDepositsResponse) GetLastID() *string {
	if c == nil {
		return nil
	}
	return c.LastID
}

func (c *CryptopayListStaticDepositsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayListStaticDepositsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListStaticDepositsResponse) SetHasMore(hasMore *bool) {
	c.HasMore = hasMore
	c.require(cryptopayListStaticDepositsResponseFieldHasMore)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListStaticDepositsResponse) SetItems(items []*CryptopayStaticDepositResponse) {
	c.Items = items
	c.require(cryptopayListStaticDepositsResponseFieldItems)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListStaticDepositsResponse) SetLastID(lastID *string) {
	c.LastID = lastID
	c.require(cryptopayListStaticDepositsResponseFieldLastID)
}

func (c *CryptopayListStaticDepositsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayListStaticDepositsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayListStaticDepositsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayListStaticDepositsResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayListStaticDepositsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayListStaticDepositsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayListStaticWalletsResponseFieldHasMore = big.NewInt(1 << 0)
	cryptopayListStaticWalletsResponseFieldItems   = big.NewInt(1 << 1)
	cryptopayListStaticWalletsResponseFieldLastID  = big.NewInt(1 << 2)
)

type CryptopayListStaticWalletsResponse struct {
	HasMore *bool                            `json:"hasMore,omitempty" url:"hasMore,omitempty"`
	Items   []*CryptopayStaticWalletResponse `json:"items,omitempty" url:"items,omitempty"`
	LastID  *string                          `json:"lastId,omitempty" url:"lastId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayListStaticWalletsResponse) GetHasMore() *bool {
	if c == nil {
		return nil
	}
	return c.HasMore
}

func (c *CryptopayListStaticWalletsResponse) GetItems() []*CryptopayStaticWalletResponse {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CryptopayListStaticWalletsResponse) GetLastID() *string {
	if c == nil {
		return nil
	}
	return c.LastID
}

func (c *CryptopayListStaticWalletsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayListStaticWalletsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListStaticWalletsResponse) SetHasMore(hasMore *bool) {
	c.HasMore = hasMore
	c.require(cryptopayListStaticWalletsResponseFieldHasMore)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListStaticWalletsResponse) SetItems(items []*CryptopayStaticWalletResponse) {
	c.Items = items
	c.require(cryptopayListStaticWalletsResponseFieldItems)
}

// SetLastID sets the LastID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayListStaticWalletsResponse) SetLastID(lastID *string) {
	c.LastID = lastID
	c.require(cryptopayListStaticWalletsResponseFieldLastID)
}

func (c *CryptopayListStaticWalletsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayListStaticWalletsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayListStaticWalletsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayListStaticWalletsResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayListStaticWalletsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayListStaticWalletsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptopayStaticDepositResponseFieldAcceptedAt     = big.NewInt(1 << 0)
	cryptopayStaticDepositResponseFieldAddress        = big.NewInt(1 << 1)
	cryptopayStaticDepositResponseFieldAmount         = big.NewInt(1 << 2)
	cryptopayStaticDepositResponseFieldAsset          = big.NewInt(1 << 3)
	cryptopayStaticDepositResponseFieldConfirmedAt    = big.NewInt(1 << 4)
	cryptopayStaticDepositResponseFieldCreatedAt      = big.NewInt(1 << 5)
	cryptopayStaticDepositResponseFieldDetectedAt     = big.NewInt(1 << 6)
	cryptopayStaticDepositResponseFieldExternalID     = big.NewInt(1 << 7)
	cryptopayStaticDepositResponseFieldFee            = big.NewInt(1 << 8)
	cryptopayStaticDepositResponseFieldID             = big.NewInt(1 << 9)
	cryptopayStaticDepositResponseFieldInvalidatedAt  = big.NewInt(1 << 10)
	cryptopayStaticDepositResponseFieldNetAmount      = big.NewInt(1 << 11)
	cryptopayStaticDepositResponseFieldNetworkFee     = big.NewInt(1 << 12)
	cryptopayStaticDepositResponseFieldProjectID      = big.NewInt(1 << 13)
	cryptopayStaticDepositResponseFieldStaticWalletID = big.NewInt(1 << 14)
	cryptopayStaticDepositResponseFieldStatus         = big.NewInt(1 << 15)
	cryptopayStaticDepositResponseFieldTransferIndex  = big.NewInt(1 << 16)
	cryptopayStaticDepositResponseFieldTxHash         = big.NewInt(1 << 17)
	cryptopayStaticDepositResponseFieldUpdatedAt      = big.NewInt(1 << 18)
)

type CryptopayStaticDepositResponse struct {
	AcceptedAt  *int              `json:"acceptedAt,omitempty" url:"acceptedAt,omitempty"`
	Address     *string           `json:"address,omitempty" url:"address,omitempty"`
	Amount      *string           `json:"amount,omitempty" url:"amount,omitempty"`
	Asset       *CryptopayAssetID `json:"asset,omitempty" url:"asset,omitempty"`
	ConfirmedAt *int              `json:"confirmedAt,omitempty" url:"confirmedAt,omitempty"`
	CreatedAt   *int              `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	DetectedAt  *int              `json:"detectedAt,omitempty" url:"detectedAt,omitempty"`
	// ExternalID is the static wallet's externalId, denormalized onto the deposit.
	ExternalID     *string                               `json:"externalId,omitempty" url:"externalId,omitempty"`
	Fee            *string                               `json:"fee,omitempty" url:"fee,omitempty"`
	ID             *string                               `json:"id,omitempty" url:"id,omitempty"`
	InvalidatedAt  *int                                  `json:"invalidatedAt,omitempty" url:"invalidatedAt,omitempty"`
	NetAmount      *string                               `json:"netAmount,omitempty" url:"netAmount,omitempty"`
	NetworkFee     *string                               `json:"networkFee,omitempty" url:"networkFee,omitempty"`
	ProjectID      *string                               `json:"projectId,omitempty" url:"projectId,omitempty"`
	StaticWalletID *string                               `json:"staticWalletId,omitempty" url:"staticWalletId,omitempty"`
	Status         *CryptopayStaticDepositResponseStatus `json:"status,omitempty" url:"status,omitempty"`
	TransferIndex  *string                               `json:"transferIndex,omitempty" url:"transferIndex,omitempty"`
	TxHash         *string                               `json:"txHash,omitempty" url:"txHash,omitempty"`
	UpdatedAt      *int                                  `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayStaticDepositResponse) GetAcceptedAt() *int {
	if c == nil {
		return nil
	}
	return c.AcceptedAt
}

func (c *CryptopayStaticDepositResponse) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CryptopayStaticDepositResponse) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CryptopayStaticDepositResponse) GetAsset() *CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.Asset
}

func (c *CryptopayStaticDepositResponse) GetConfirmedAt() *int {
	if c == nil {
		return nil
	}
	return c.ConfirmedAt
}

func (c *CryptopayStaticDepositResponse) GetCreatedAt() *int {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CryptopayStaticDepositResponse) GetDetectedAt() *int {
	if c == nil {
		return nil
	}
	return c.DetectedAt
}

func (c *CryptopayStaticDepositResponse) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CryptopayStaticDepositResponse) GetFee() *string {
	if c == nil {
		return nil
	}
	return c.Fee
}

func (c *CryptopayStaticDepositResponse) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CryptopayStaticDepositResponse) GetInvalidatedAt() *int {
	if c == nil {
		return nil
	}
	return c.InvalidatedAt
}

func (c *CryptopayStaticDepositResponse) GetNetAmount() *string {
	if c == nil {
		return nil
	}
	return c.NetAmount
}

func (c *CryptopayStaticDepositResponse) GetNetworkFee() *string {
	if c == nil {
		return nil
	}
	return c.NetworkFee
}

func (c *CryptopayStaticDepositResponse) GetProjectID() *string {
	if c == nil {
		return nil
	}
	return c.ProjectID
}

func (c *CryptopayStaticDepositResponse) GetStaticWalletID() *string {
	if c == nil {
		return nil
	}
	return c.StaticWalletID
}

func (c *CryptopayStaticDepositResponse) GetStatus() *CryptopayStaticDepositResponseStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CryptopayStaticDepositResponse) GetTransferIndex() *string {
	if c == nil {
		return nil
	}
	return c.TransferIndex
}

func (c *CryptopayStaticDepositResponse) GetTxHash() *string {
	if c == nil {
		return nil
	}
	return c.TxHash
}

func (c *CryptopayStaticDepositResponse) GetUpdatedAt() *int {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CryptopayStaticDepositResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayStaticDepositResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAcceptedAt sets the AcceptedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetAcceptedAt(acceptedAt *int) {
	c.AcceptedAt = acceptedAt
	c.require(cryptopayStaticDepositResponseFieldAcceptedAt)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetAddress(address *string) {
	c.Address = address
	c.require(cryptopayStaticDepositResponseFieldAddress)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetAmount(amount *string) {
	c.Amount = amount
	c.require(cryptopayStaticDepositResponseFieldAmount)
}

// SetAsset sets the Asset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetAsset(asset *CryptopayAssetID) {
	c.Asset = asset
	c.require(cryptopayStaticDepositResponseFieldAsset)
}

// SetConfirmedAt sets the ConfirmedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetConfirmedAt(confirmedAt *int) {
	c.ConfirmedAt = confirmedAt
	c.require(cryptopayStaticDepositResponseFieldConfirmedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetCreatedAt(createdAt *int) {
	c.CreatedAt = createdAt
	c.require(cryptopayStaticDepositResponseFieldCreatedAt)
}

// SetDetectedAt sets the DetectedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetDetectedAt(detectedAt *int) {
	c.DetectedAt = detectedAt
	c.require(cryptopayStaticDepositResponseFieldDetectedAt)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(cryptopayStaticDepositResponseFieldExternalID)
}

// SetFee sets the Fee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetFee(fee *string) {
	c.Fee = fee
	c.require(cryptopayStaticDepositResponseFieldFee)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetID(id *string) {
	c.ID = id
	c.require(cryptopayStaticDepositResponseFieldID)
}

// SetInvalidatedAt sets the InvalidatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetInvalidatedAt(invalidatedAt *int) {
	c.InvalidatedAt = invalidatedAt
	c.require(cryptopayStaticDepositResponseFieldInvalidatedAt)
}

// SetNetAmount sets the NetAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetNetAmount(netAmount *string) {
	c.NetAmount = netAmount
	c.require(cryptopayStaticDepositResponseFieldNetAmount)
}

// SetNetworkFee sets the NetworkFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetNetworkFee(networkFee *string) {
	c.NetworkFee = networkFee
	c.require(cryptopayStaticDepositResponseFieldNetworkFee)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetProjectID(projectID *string) {
	c.ProjectID = projectID
	c.require(cryptopayStaticDepositResponseFieldProjectID)
}

// SetStaticWalletID sets the StaticWalletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetStaticWalletID(staticWalletID *string) {
	c.StaticWalletID = staticWalletID
	c.require(cryptopayStaticDepositResponseFieldStaticWalletID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetStatus(status *CryptopayStaticDepositResponseStatus) {
	c.Status = status
	c.require(cryptopayStaticDepositResponseFieldStatus)
}

// SetTransferIndex sets the TransferIndex field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetTransferIndex(transferIndex *string) {
	c.TransferIndex = transferIndex
	c.require(cryptopayStaticDepositResponseFieldTransferIndex)
}

// SetTxHash sets the TxHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetTxHash(txHash *string) {
	c.TxHash = txHash
	c.require(cryptopayStaticDepositResponseFieldTxHash)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticDepositResponse) SetUpdatedAt(updatedAt *int) {
	c.UpdatedAt = updatedAt
	c.require(cryptopayStaticDepositResponseFieldUpdatedAt)
}

func (c *CryptopayStaticDepositResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayStaticDepositResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayStaticDepositResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayStaticDepositResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayStaticDepositResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayStaticDepositResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CryptopayStaticDepositResponseStatus string

const (
	CryptopayStaticDepositResponseStatusDetected    CryptopayStaticDepositResponseStatus = "detected"
	CryptopayStaticDepositResponseStatusAccepted    CryptopayStaticDepositResponseStatus = "accepted"
	CryptopayStaticDepositResponseStatusConfirmed   CryptopayStaticDepositResponseStatus = "confirmed"
	CryptopayStaticDepositResponseStatusIgnored     CryptopayStaticDepositResponseStatus = "ignored"
	CryptopayStaticDepositResponseStatusInvalidated CryptopayStaticDepositResponseStatus = "invalidated"
)

func NewCryptopayStaticDepositResponseStatusFromString(s string) (CryptopayStaticDepositResponseStatus, error) {
	switch s {
	case "detected":
		return CryptopayStaticDepositResponseStatusDetected, nil
	case "accepted":
		return CryptopayStaticDepositResponseStatusAccepted, nil
	case "confirmed":
		return CryptopayStaticDepositResponseStatusConfirmed, nil
	case "ignored":
		return CryptopayStaticDepositResponseStatusIgnored, nil
	case "invalidated":
		return CryptopayStaticDepositResponseStatusInvalidated, nil
	}
	var t CryptopayStaticDepositResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayStaticDepositResponseStatus) Ptr() *CryptopayStaticDepositResponseStatus {
	return &c
}

var (
	cryptopayStaticWalletResponseFieldAddress       = big.NewInt(1 << 0)
	cryptopayStaticWalletResponseFieldAllowedAssets = big.NewInt(1 << 1)
	cryptopayStaticWalletResponseFieldCreatedAt     = big.NewInt(1 << 2)
	cryptopayStaticWalletResponseFieldExternalID    = big.NewInt(1 << 3)
	cryptopayStaticWalletResponseFieldID            = big.NewInt(1 << 4)
	cryptopayStaticWalletResponseFieldIsTest        = big.NewInt(1 << 5)
	cryptopayStaticWalletResponseFieldMetadata      = big.NewInt(1 << 6)
	cryptopayStaticWalletResponseFieldProjectID     = big.NewInt(1 << 7)
	cryptopayStaticWalletResponseFieldUpdatedAt     = big.NewInt(1 << 8)
	cryptopayStaticWalletResponseFieldWebhookURL    = big.NewInt(1 << 9)
)

type CryptopayStaticWalletResponse struct {
	Address       *string            `json:"address,omitempty" url:"address,omitempty"`
	AllowedAssets []CryptopayAssetID `json:"allowedAssets,omitempty" url:"allowedAssets,omitempty"`
	CreatedAt     *int               `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	ExternalID    *string            `json:"externalId,omitempty" url:"externalId,omitempty"`
	ID            *string            `json:"id,omitempty" url:"id,omitempty"`
	IsTest        *bool              `json:"isTest,omitempty" url:"isTest,omitempty"`
	Metadata      map[string]any     `json:"metadata,omitempty" url:"metadata,omitempty"`
	ProjectID     *string            `json:"projectId,omitempty" url:"projectId,omitempty"`
	UpdatedAt     *int               `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`
	WebhookURL    *string            `json:"webhookUrl,omitempty" url:"webhookUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptopayStaticWalletResponse) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CryptopayStaticWalletResponse) GetAllowedAssets() []CryptopayAssetID {
	if c == nil {
		return nil
	}
	return c.AllowedAssets
}

func (c *CryptopayStaticWalletResponse) GetCreatedAt() *int {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CryptopayStaticWalletResponse) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CryptopayStaticWalletResponse) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CryptopayStaticWalletResponse) GetIsTest() *bool {
	if c == nil {
		return nil
	}
	return c.IsTest
}

func (c *CryptopayStaticWalletResponse) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CryptopayStaticWalletResponse) GetProjectID() *string {
	if c == nil {
		return nil
	}
	return c.ProjectID
}

func (c *CryptopayStaticWalletResponse) GetUpdatedAt() *int {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CryptopayStaticWalletResponse) GetWebhookURL() *string {
	if c == nil {
		return nil
	}
	return c.WebhookURL
}

func (c *CryptopayStaticWalletResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptopayStaticWalletResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetAddress(address *string) {
	c.Address = address
	c.require(cryptopayStaticWalletResponseFieldAddress)
}

// SetAllowedAssets sets the AllowedAssets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetAllowedAssets(allowedAssets []CryptopayAssetID) {
	c.AllowedAssets = allowedAssets
	c.require(cryptopayStaticWalletResponseFieldAllowedAssets)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetCreatedAt(createdAt *int) {
	c.CreatedAt = createdAt
	c.require(cryptopayStaticWalletResponseFieldCreatedAt)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(cryptopayStaticWalletResponseFieldExternalID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetID(id *string) {
	c.ID = id
	c.require(cryptopayStaticWalletResponseFieldID)
}

// SetIsTest sets the IsTest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetIsTest(isTest *bool) {
	c.IsTest = isTest
	c.require(cryptopayStaticWalletResponseFieldIsTest)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(cryptopayStaticWalletResponseFieldMetadata)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetProjectID(projectID *string) {
	c.ProjectID = projectID
	c.require(cryptopayStaticWalletResponseFieldProjectID)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetUpdatedAt(updatedAt *int) {
	c.UpdatedAt = updatedAt
	c.require(cryptopayStaticWalletResponseFieldUpdatedAt)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayStaticWalletResponse) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cryptopayStaticWalletResponseFieldWebhookURL)
}

func (c *CryptopayStaticWalletResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayStaticWalletResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptopayStaticWalletResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptopayStaticWalletResponse) MarshalJSON() ([]byte, error) {
	type embed CryptopayStaticWalletResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptopayStaticWalletResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CryptopaySimulateStaticDepositRequestStatus string

const (
	CryptopaySimulateStaticDepositRequestStatusDetected    CryptopaySimulateStaticDepositRequestStatus = "detected"
	CryptopaySimulateStaticDepositRequestStatusAccepted    CryptopaySimulateStaticDepositRequestStatus = "accepted"
	CryptopaySimulateStaticDepositRequestStatusConfirmed   CryptopaySimulateStaticDepositRequestStatus = "confirmed"
	CryptopaySimulateStaticDepositRequestStatusInvalidated CryptopaySimulateStaticDepositRequestStatus = "invalidated"
)

func NewCryptopaySimulateStaticDepositRequestStatusFromString(s string) (CryptopaySimulateStaticDepositRequestStatus, error) {
	switch s {
	case "detected":
		return CryptopaySimulateStaticDepositRequestStatusDetected, nil
	case "accepted":
		return CryptopaySimulateStaticDepositRequestStatusAccepted, nil
	case "confirmed":
		return CryptopaySimulateStaticDepositRequestStatusConfirmed, nil
	case "invalidated":
		return CryptopaySimulateStaticDepositRequestStatusInvalidated, nil
	}
	var t CryptopaySimulateStaticDepositRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopaySimulateStaticDepositRequestStatus) Ptr() *CryptopaySimulateStaticDepositRequestStatus {
	return &c
}

type GetV1StaticWalletsRequestOrder string

const (
	GetV1StaticWalletsRequestOrderAsc  GetV1StaticWalletsRequestOrder = "asc"
	GetV1StaticWalletsRequestOrderDesc GetV1StaticWalletsRequestOrder = "desc"
)

func NewGetV1StaticWalletsRequestOrderFromString(s string) (GetV1StaticWalletsRequestOrder, error) {
	switch s {
	case "asc":
		return GetV1StaticWalletsRequestOrderAsc, nil
	case "desc":
		return GetV1StaticWalletsRequestOrderDesc, nil
	}
	var t GetV1StaticWalletsRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetV1StaticWalletsRequestOrder) Ptr() *GetV1StaticWalletsRequestOrder {
	return &g
}

type GetV1StaticWalletsStaticWalletIDDepositsRequestOrder string

const (
	GetV1StaticWalletsStaticWalletIDDepositsRequestOrderAsc  GetV1StaticWalletsStaticWalletIDDepositsRequestOrder = "asc"
	GetV1StaticWalletsStaticWalletIDDepositsRequestOrderDesc GetV1StaticWalletsStaticWalletIDDepositsRequestOrder = "desc"
)

func NewGetV1StaticWalletsStaticWalletIDDepositsRequestOrderFromString(s string) (GetV1StaticWalletsStaticWalletIDDepositsRequestOrder, error) {
	switch s {
	case "asc":
		return GetV1StaticWalletsStaticWalletIDDepositsRequestOrderAsc, nil
	case "desc":
		return GetV1StaticWalletsStaticWalletIDDepositsRequestOrderDesc, nil
	}
	var t GetV1StaticWalletsStaticWalletIDDepositsRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetV1StaticWalletsStaticWalletIDDepositsRequestOrder) Ptr() *GetV1StaticWalletsStaticWalletIDDepositsRequestOrder {
	return &g
}

var (
	cryptopayUpdateStaticWalletRequestFieldStaticWalletID = big.NewInt(1 << 0)
	cryptopayUpdateStaticWalletRequestFieldAllowedAssets  = big.NewInt(1 << 1)
	cryptopayUpdateStaticWalletRequestFieldMetadata       = big.NewInt(1 << 2)
	cryptopayUpdateStaticWalletRequestFieldWebhookURL     = big.NewInt(1 << 3)
)

type CryptopayUpdateStaticWalletRequest struct {
	// Static wallet ID
	StaticWalletID string             `json:"-" url:"-"`
	AllowedAssets  []CryptopayAssetID `json:"allowedAssets,omitempty" url:"-"`
	Metadata       map[string]any     `json:"metadata,omitempty" url:"-"`
	WebhookURL     *string            `json:"webhookUrl,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptopayUpdateStaticWalletRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetStaticWalletID sets the StaticWalletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayUpdateStaticWalletRequest) SetStaticWalletID(staticWalletID string) {
	c.StaticWalletID = staticWalletID
	c.require(cryptopayUpdateStaticWalletRequestFieldStaticWalletID)
}

// SetAllowedAssets sets the AllowedAssets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayUpdateStaticWalletRequest) SetAllowedAssets(allowedAssets []CryptopayAssetID) {
	c.AllowedAssets = allowedAssets
	c.require(cryptopayUpdateStaticWalletRequestFieldAllowedAssets)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayUpdateStaticWalletRequest) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(cryptopayUpdateStaticWalletRequestFieldMetadata)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptopayUpdateStaticWalletRequest) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(cryptopayUpdateStaticWalletRequestFieldWebhookURL)
}

func (c *CryptopayUpdateStaticWalletRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptopayUpdateStaticWalletRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CryptopayUpdateStaticWalletRequest(body)
	return nil
}

func (c *CryptopayUpdateStaticWalletRequest) MarshalJSON() ([]byte, error) {
	type embed CryptopayUpdateStaticWalletRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}
