// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	big "math/big"
)

var (
	controllerErrorResponseFieldArgs      = big.NewInt(1 << 0)
	controllerErrorResponseFieldErrorCode = big.NewInt(1 << 1)
	controllerErrorResponseFieldMessage   = big.NewInt(1 << 2)
)

type ControllerErrorResponse struct {
	// Optional list of values interpolated into the error message template (e.g. field names or limits). Order matches the placeholders in the message.
	Args []any `json:"args,omitempty" url:"args,omitempty"`
	// Stable numeric application error code identifying the error type. Use it for programmatic handling; it does not change across locales or message wording.
	ErrorCode *int `json:"errorCode,omitempty" url:"errorCode,omitempty"`
	// Human-readable description of what went wrong. Intended for logging and debugging, not for programmatic branching (use errorCode for that).
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ControllerErrorResponse) GetArgs() []any {
	if c == nil {
		return nil
	}
	return c.Args
}

func (c *ControllerErrorResponse) GetErrorCode() *int {
	if c == nil {
		return nil
	}
	return c.ErrorCode
}

func (c *ControllerErrorResponse) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *ControllerErrorResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ControllerErrorResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ControllerErrorResponse) SetArgs(args []any) {
	c.Args = args
	c.require(controllerErrorResponseFieldArgs)
}

// SetErrorCode sets the ErrorCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ControllerErrorResponse) SetErrorCode(errorCode *int) {
	c.ErrorCode = errorCode
	c.require(controllerErrorResponseFieldErrorCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ControllerErrorResponse) SetMessage(message *string) {
	c.Message = message
	c.require(controllerErrorResponseFieldMessage)
}

func (c *ControllerErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ControllerErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ControllerErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ControllerErrorResponse) MarshalJSON() ([]byte, error) {
	type embed ControllerErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ControllerErrorResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Asset id-string (see GET /v1/assets), e.g. USDT_ETHEREUM.
type CryptopayAssetID string

const (
	CryptopayAssetIDUsdtEthereum           CryptopayAssetID = "USDT_ETHEREUM"
	CryptopayAssetIDUsdtArbitrum           CryptopayAssetID = "USDT_ARBITRUM"
	CryptopayAssetIDUsdtOptimism           CryptopayAssetID = "USDT_OPTIMISM"
	CryptopayAssetIDUsdtBase               CryptopayAssetID = "USDT_BASE"
	CryptopayAssetIDUsdtBsc                CryptopayAssetID = "USDT_BSC"
	CryptopayAssetIDUsdtPlasma             CryptopayAssetID = "USDT_PLASMA"
	CryptopayAssetIDUsdtPolygon            CryptopayAssetID = "USDT_POLYGON"
	CryptopayAssetIDUsdcEthereum           CryptopayAssetID = "USDC_ETHEREUM"
	CryptopayAssetIDUsdcArbitrum           CryptopayAssetID = "USDC_ARBITRUM"
	CryptopayAssetIDUsdCeArbitrum          CryptopayAssetID = "USDCE_ARBITRUM"
	CryptopayAssetIDUsdcOptimism           CryptopayAssetID = "USDC_OPTIMISM"
	CryptopayAssetIDUsdcBase               CryptopayAssetID = "USDC_BASE"
	CryptopayAssetIDUsdcBsc                CryptopayAssetID = "USDC_BSC"
	CryptopayAssetIDUsdcPlasma             CryptopayAssetID = "USDC_PLASMA"
	CryptopayAssetIDUsdcPolygon            CryptopayAssetID = "USDC_POLYGON"
	CryptopayAssetIDEthEthereum            CryptopayAssetID = "ETH_ETHEREUM"
	CryptopayAssetIDEthArbitrum            CryptopayAssetID = "ETH_ARBITRUM"
	CryptopayAssetIDEthOptimism            CryptopayAssetID = "ETH_OPTIMISM"
	CryptopayAssetIDEthBase                CryptopayAssetID = "ETH_BASE"
	CryptopayAssetIDXplPlasma              CryptopayAssetID = "XPL_PLASMA"
	CryptopayAssetIDBnbBsc                 CryptopayAssetID = "BNB_BSC"
	CryptopayAssetIDPolPolygon             CryptopayAssetID = "POL_POLYGON"
	CryptopayAssetIDTestcoinEthereum       CryptopayAssetID = "TESTCOIN_ETHEREUM"
	CryptopayAssetIDTestcoinOptimism       CryptopayAssetID = "TESTCOIN_OPTIMISM"
	CryptopayAssetIDTestcoinPlasma         CryptopayAssetID = "TESTCOIN_PLASMA"
	CryptopayAssetIDTeststablecoinEthereum CryptopayAssetID = "TESTSTABLECOIN_ETHEREUM"
	CryptopayAssetIDTeststablecoinOptimism CryptopayAssetID = "TESTSTABLECOIN_OPTIMISM"
	CryptopayAssetIDTeststablecoinPlasma   CryptopayAssetID = "TESTSTABLECOIN_PLASMA"
)

func NewCryptopayAssetIDFromString(s string) (CryptopayAssetID, error) {
	switch s {
	case "USDT_ETHEREUM":
		return CryptopayAssetIDUsdtEthereum, nil
	case "USDT_ARBITRUM":
		return CryptopayAssetIDUsdtArbitrum, nil
	case "USDT_OPTIMISM":
		return CryptopayAssetIDUsdtOptimism, nil
	case "USDT_BASE":
		return CryptopayAssetIDUsdtBase, nil
	case "USDT_BSC":
		return CryptopayAssetIDUsdtBsc, nil
	case "USDT_PLASMA":
		return CryptopayAssetIDUsdtPlasma, nil
	case "USDT_POLYGON":
		return CryptopayAssetIDUsdtPolygon, nil
	case "USDC_ETHEREUM":
		return CryptopayAssetIDUsdcEthereum, nil
	case "USDC_ARBITRUM":
		return CryptopayAssetIDUsdcArbitrum, nil
	case "USDCE_ARBITRUM":
		return CryptopayAssetIDUsdCeArbitrum, nil
	case "USDC_OPTIMISM":
		return CryptopayAssetIDUsdcOptimism, nil
	case "USDC_BASE":
		return CryptopayAssetIDUsdcBase, nil
	case "USDC_BSC":
		return CryptopayAssetIDUsdcBsc, nil
	case "USDC_PLASMA":
		return CryptopayAssetIDUsdcPlasma, nil
	case "USDC_POLYGON":
		return CryptopayAssetIDUsdcPolygon, nil
	case "ETH_ETHEREUM":
		return CryptopayAssetIDEthEthereum, nil
	case "ETH_ARBITRUM":
		return CryptopayAssetIDEthArbitrum, nil
	case "ETH_OPTIMISM":
		return CryptopayAssetIDEthOptimism, nil
	case "ETH_BASE":
		return CryptopayAssetIDEthBase, nil
	case "XPL_PLASMA":
		return CryptopayAssetIDXplPlasma, nil
	case "BNB_BSC":
		return CryptopayAssetIDBnbBsc, nil
	case "POL_POLYGON":
		return CryptopayAssetIDPolPolygon, nil
	case "TESTCOIN_ETHEREUM":
		return CryptopayAssetIDTestcoinEthereum, nil
	case "TESTCOIN_OPTIMISM":
		return CryptopayAssetIDTestcoinOptimism, nil
	case "TESTCOIN_PLASMA":
		return CryptopayAssetIDTestcoinPlasma, nil
	case "TESTSTABLECOIN_ETHEREUM":
		return CryptopayAssetIDTeststablecoinEthereum, nil
	case "TESTSTABLECOIN_OPTIMISM":
		return CryptopayAssetIDTeststablecoinOptimism, nil
	case "TESTSTABLECOIN_PLASMA":
		return CryptopayAssetIDTeststablecoinPlasma, nil
	}
	var t CryptopayAssetID
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CryptopayAssetID) Ptr() *CryptopayAssetID {
	return &c
}

// Webhook body for a payment lifecycle transition. Signed over the raw body with the project's Ed25519 key; verify with project.webhookPublicKey. `createdAt` is the signed, trusted timestamp; `payment` is the full payment resource (the same shape as the merchant GET /v1/payments/{paymentId} view). Obtain `webhookPublicKey` from your project settings in the Suward dashboard.
var (
	webhookPaymentEventFieldType      = big.NewInt(1 << 0)
	webhookPaymentEventFieldEventID   = big.NewInt(1 << 1)
	webhookPaymentEventFieldCreatedAt = big.NewInt(1 << 2)
	webhookPaymentEventFieldPayment   = big.NewInt(1 << 3)
)

type WebhookPaymentEvent struct {
	// Event type. payment.accepted: safe confirmations reached and the balance was credited (non-final). payment.success: the payment finalized (terminal). payment.failed: the payment failed or expired without a valid payment (terminal).
	Type WebhookPaymentEventType `json:"type" url:"type"`
	// Unique identifier of this event. The same event may be redelivered on retry; use eventId to deduplicate.
	EventID string `json:"eventId" url:"eventId"`
	// Event creation time, unix milliseconds.
	CreatedAt int64 `json:"createdAt" url:"createdAt"`
	// Full payment resource at the time of the event — the same shape as the merchant GET /v1/payments/{paymentId} view.
	Payment *CryptopayPaymentResponse `json:"payment" url:"payment"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookPaymentEvent) GetType() WebhookPaymentEventType {
	if w == nil {
		return ""
	}
	return w.Type
}

func (w *WebhookPaymentEvent) GetEventID() string {
	if w == nil {
		return ""
	}
	return w.EventID
}

func (w *WebhookPaymentEvent) GetCreatedAt() int64 {
	if w == nil {
		return 0
	}
	return w.CreatedAt
}

func (w *WebhookPaymentEvent) GetPayment() *CryptopayPaymentResponse {
	if w == nil {
		return nil
	}
	return w.Payment
}

func (w *WebhookPaymentEvent) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookPaymentEvent) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookPaymentEvent) SetType(type_ WebhookPaymentEventType) {
	w.Type = type_
	w.require(webhookPaymentEventFieldType)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookPaymentEvent) SetEventID(eventID string) {
	w.EventID = eventID
	w.require(webhookPaymentEventFieldEventID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookPaymentEvent) SetCreatedAt(createdAt int64) {
	w.CreatedAt = createdAt
	w.require(webhookPaymentEventFieldCreatedAt)
}

// SetPayment sets the Payment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookPaymentEvent) SetPayment(payment *CryptopayPaymentResponse) {
	w.Payment = payment
	w.require(webhookPaymentEventFieldPayment)
}

func (w *WebhookPaymentEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookPaymentEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookPaymentEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookPaymentEvent) MarshalJSON() ([]byte, error) {
	type embed WebhookPaymentEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookPaymentEvent) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Event type. payment.accepted: safe confirmations reached and the balance was credited (non-final). payment.success: the payment finalized (terminal). payment.failed: the payment failed or expired without a valid payment (terminal).
type WebhookPaymentEventType string

const (
	WebhookPaymentEventTypePaymentAccepted WebhookPaymentEventType = "payment.accepted"
	WebhookPaymentEventTypePaymentSuccess  WebhookPaymentEventType = "payment.success"
	WebhookPaymentEventTypePaymentFailed   WebhookPaymentEventType = "payment.failed"
)

func NewWebhookPaymentEventTypeFromString(s string) (WebhookPaymentEventType, error) {
	switch s {
	case "payment.accepted":
		return WebhookPaymentEventTypePaymentAccepted, nil
	case "payment.success":
		return WebhookPaymentEventTypePaymentSuccess, nil
	case "payment.failed":
		return WebhookPaymentEventTypePaymentFailed, nil
	}
	var t WebhookPaymentEventType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WebhookPaymentEventType) Ptr() *WebhookPaymentEventType {
	return &w
}

// Webhook body for a static-wallet deposit transition. Signed over the raw body with the project's Ed25519 key; verify with project.webhookPublicKey. `createdAt` is the signed, trusted timestamp; `staticDeposit` is the full deposit resource. Obtain `webhookPublicKey` from your project settings in the Suward dashboard.
var (
	webhookStaticDepositEventFieldType          = big.NewInt(1 << 0)
	webhookStaticDepositEventFieldEventID       = big.NewInt(1 << 1)
	webhookStaticDepositEventFieldCreatedAt     = big.NewInt(1 << 2)
	webhookStaticDepositEventFieldStaticDeposit = big.NewInt(1 << 3)
)

type WebhookStaticDepositEvent struct {
	// Event type. static_deposit.accepted: the deposit reached safe confirmations and was credited (non-final). static_deposit.success: the deposit finalized (terminal).
	Type WebhookStaticDepositEventType `json:"type" url:"type"`
	// Unique identifier of this event. The same event may be redelivered on retry; use eventId to deduplicate.
	EventID string `json:"eventId" url:"eventId"`
	// Event creation time, unix milliseconds.
	CreatedAt int64 `json:"createdAt" url:"createdAt"`
	// Full static-wallet deposit resource at the time of the event.
	StaticDeposit *CryptopayStaticDepositResponse `json:"staticDeposit" url:"staticDeposit"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookStaticDepositEvent) GetType() WebhookStaticDepositEventType {
	if w == nil {
		return ""
	}
	return w.Type
}

func (w *WebhookStaticDepositEvent) GetEventID() string {
	if w == nil {
		return ""
	}
	return w.EventID
}

func (w *WebhookStaticDepositEvent) GetCreatedAt() int64 {
	if w == nil {
		return 0
	}
	return w.CreatedAt
}

func (w *WebhookStaticDepositEvent) GetStaticDeposit() *CryptopayStaticDepositResponse {
	if w == nil {
		return nil
	}
	return w.StaticDeposit
}

func (w *WebhookStaticDepositEvent) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookStaticDepositEvent) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookStaticDepositEvent) SetType(type_ WebhookStaticDepositEventType) {
	w.Type = type_
	w.require(webhookStaticDepositEventFieldType)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookStaticDepositEvent) SetEventID(eventID string) {
	w.EventID = eventID
	w.require(webhookStaticDepositEventFieldEventID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookStaticDepositEvent) SetCreatedAt(createdAt int64) {
	w.CreatedAt = createdAt
	w.require(webhookStaticDepositEventFieldCreatedAt)
}

// SetStaticDeposit sets the StaticDeposit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookStaticDepositEvent) SetStaticDeposit(staticDeposit *CryptopayStaticDepositResponse) {
	w.StaticDeposit = staticDeposit
	w.require(webhookStaticDepositEventFieldStaticDeposit)
}

func (w *WebhookStaticDepositEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookStaticDepositEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookStaticDepositEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookStaticDepositEvent) MarshalJSON() ([]byte, error) {
	type embed WebhookStaticDepositEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookStaticDepositEvent) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Event type. static_deposit.accepted: the deposit reached safe confirmations and was credited (non-final). static_deposit.success: the deposit finalized (terminal).
type WebhookStaticDepositEventType string

const (
	WebhookStaticDepositEventTypeStaticDepositAccepted WebhookStaticDepositEventType = "static_deposit.accepted"
	WebhookStaticDepositEventTypeStaticDepositSuccess  WebhookStaticDepositEventType = "static_deposit.success"
)

func NewWebhookStaticDepositEventTypeFromString(s string) (WebhookStaticDepositEventType, error) {
	switch s {
	case "static_deposit.accepted":
		return WebhookStaticDepositEventTypeStaticDepositAccepted, nil
	case "static_deposit.success":
		return WebhookStaticDepositEventTypeStaticDepositSuccess, nil
	}
	var t WebhookStaticDepositEventType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WebhookStaticDepositEventType) Ptr() *WebhookStaticDepositEventType {
	return &w
}
