// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersControllerErrorResponse(t *testing.T) {
	t.Run("SetArgs", func(t *testing.T) {
		obj := &ControllerErrorResponse{}
		var fernTestValueArgs []any
		obj.SetArgs(fernTestValueArgs)
		assert.Equal(t, fernTestValueArgs, obj.Args)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetErrorCode", func(t *testing.T) {
		obj := &ControllerErrorResponse{}
		var fernTestValueErrorCode *int
		obj.SetErrorCode(fernTestValueErrorCode)
		assert.Equal(t, fernTestValueErrorCode, obj.ErrorCode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMessage", func(t *testing.T) {
		obj := &ControllerErrorResponse{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersControllerErrorResponse(t *testing.T) {
	t.Run("GetArgs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		var expected []any
		obj.Args = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetArgs(), "getter should return the property value")
	})

	t.Run("GetArgs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		obj.Args = nil

		// Act & Assert
		assert.Nil(t, obj.GetArgs(), "getter should return nil when property is nil")
	})

	t.Run("GetArgs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ControllerErrorResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetArgs() // Should return zero value
	})

	t.Run("GetErrorCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		var expected *int
		obj.ErrorCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetErrorCode(), "getter should return the property value")
	})

	t.Run("GetErrorCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		obj.ErrorCode = nil

		// Act & Assert
		assert.Nil(t, obj.GetErrorCode(), "getter should return nil when property is nil")
	})

	t.Run("GetErrorCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ControllerErrorResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetErrorCode() // Should return zero value
	})

	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		var expected *string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		obj.Message = nil

		// Act & Assert
		assert.Nil(t, obj.GetMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ControllerErrorResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

}

func TestSettersMarkExplicitControllerErrorResponse(t *testing.T) {
	t.Run("SetArgs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		var fernTestValueArgs []any

		// Act
		obj.SetArgs(fernTestValueArgs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetErrorCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		var fernTestValueErrorCode *int

		// Act
		obj.SetErrorCode(fernTestValueErrorCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookPaymentEvent(t *testing.T) {
	t.Run("SetType", func(t *testing.T) {
		obj := &WebhookPaymentEvent{}
		var fernTestValueType WebhookPaymentEventType
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEventID", func(t *testing.T) {
		obj := &WebhookPaymentEvent{}
		var fernTestValueEventID string
		obj.SetEventID(fernTestValueEventID)
		assert.Equal(t, fernTestValueEventID, obj.EventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &WebhookPaymentEvent{}
		var fernTestValueCreatedAt int64
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPayment", func(t *testing.T) {
		obj := &WebhookPaymentEvent{}
		var fernTestValuePayment *CryptopayPaymentResponse
		obj.SetPayment(fernTestValuePayment)
		assert.Equal(t, fernTestValuePayment, obj.Payment)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookPaymentEvent(t *testing.T) {
	t.Run("GetType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var expected WebhookPaymentEventType
		obj.Type = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetType(), "getter should return the property value")
	})

	t.Run("GetType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookPaymentEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetType() // Should return zero value
	})

	t.Run("GetEventID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var expected string
		obj.EventID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEventID(), "getter should return the property value")
	})

	t.Run("GetEventID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookPaymentEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEventID() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var expected int64
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookPaymentEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetPayment", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var expected *CryptopayPaymentResponse
		obj.Payment = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPayment(), "getter should return the property value")
	})

	t.Run("GetPayment_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		obj.Payment = nil

		// Act & Assert
		assert.Nil(t, obj.GetPayment(), "getter should return nil when property is nil")
	})

	t.Run("GetPayment_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookPaymentEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPayment() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookPaymentEvent(t *testing.T) {
	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var fernTestValueType WebhookPaymentEventType

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var fernTestValueEventID string

		// Act
		obj.SetEventID(fernTestValueEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var fernTestValueCreatedAt int64

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPayment_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}
		var fernTestValuePayment *CryptopayPaymentResponse

		// Act
		obj.SetPayment(fernTestValuePayment)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookStaticDepositEvent(t *testing.T) {
	t.Run("SetType", func(t *testing.T) {
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueType WebhookStaticDepositEventType
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEventID", func(t *testing.T) {
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueEventID string
		obj.SetEventID(fernTestValueEventID)
		assert.Equal(t, fernTestValueEventID, obj.EventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueCreatedAt int64
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStaticDeposit", func(t *testing.T) {
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueStaticDeposit *CryptopayStaticDepositResponse
		obj.SetStaticDeposit(fernTestValueStaticDeposit)
		assert.Equal(t, fernTestValueStaticDeposit, obj.StaticDeposit)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookStaticDepositEvent(t *testing.T) {
	t.Run("GetType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var expected WebhookStaticDepositEventType
		obj.Type = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetType(), "getter should return the property value")
	})

	t.Run("GetType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookStaticDepositEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetType() // Should return zero value
	})

	t.Run("GetEventID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var expected string
		obj.EventID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEventID(), "getter should return the property value")
	})

	t.Run("GetEventID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookStaticDepositEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEventID() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var expected int64
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookStaticDepositEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetStaticDeposit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var expected *CryptopayStaticDepositResponse
		obj.StaticDeposit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStaticDeposit(), "getter should return the property value")
	})

	t.Run("GetStaticDeposit_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		obj.StaticDeposit = nil

		// Act & Assert
		assert.Nil(t, obj.GetStaticDeposit(), "getter should return nil when property is nil")
	})

	t.Run("GetStaticDeposit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookStaticDepositEvent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStaticDeposit() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookStaticDepositEvent(t *testing.T) {
	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueType WebhookStaticDepositEventType

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueEventID string

		// Act
		obj.SetEventID(fernTestValueEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueCreatedAt int64

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStaticDeposit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}
		var fernTestValueStaticDeposit *CryptopayStaticDepositResponse

		// Act
		obj.SetStaticDeposit(fernTestValueStaticDeposit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingControllerErrorResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ControllerErrorResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ControllerErrorResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ControllerErrorResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ControllerErrorResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWebhookPaymentEvent(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookPaymentEvent{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookPaymentEvent
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookPaymentEvent
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WebhookPaymentEvent
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWebhookStaticDepositEvent(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookStaticDepositEvent{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookStaticDepositEvent
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookStaticDepositEvent
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WebhookStaticDepositEvent
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringControllerErrorResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ControllerErrorResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ControllerErrorResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookPaymentEvent(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookPaymentEvent{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookPaymentEvent
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookStaticDepositEvent(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookStaticDepositEvent{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookStaticDepositEvent
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCryptopayAssetID(t *testing.T) {
	t.Run("NewFromString_USDT_ETHEREUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDT_ETHEREUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDT_ETHEREUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDT_ARBITRUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDT_ARBITRUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDT_ARBITRUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDT_OPTIMISM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDT_OPTIMISM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDT_OPTIMISM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDT_BASE", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDT_BASE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDT_BASE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDT_BSC", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDT_BSC")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDT_BSC"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDT_PLASMA", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDT_PLASMA")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDT_PLASMA"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDT_POLYGON", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDT_POLYGON")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDT_POLYGON"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDC_ETHEREUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDC_ETHEREUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDC_ETHEREUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDC_ARBITRUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDC_ARBITRUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDC_ARBITRUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDCE_ARBITRUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDCE_ARBITRUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDCE_ARBITRUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDC_OPTIMISM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDC_OPTIMISM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDC_OPTIMISM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDC_BASE", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDC_BASE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDC_BASE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDC_BSC", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDC_BSC")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDC_BSC"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDC_PLASMA", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDC_PLASMA")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDC_PLASMA"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USDC_POLYGON", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("USDC_POLYGON")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("USDC_POLYGON"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ETH_ETHEREUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("ETH_ETHEREUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("ETH_ETHEREUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ETH_ARBITRUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("ETH_ARBITRUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("ETH_ARBITRUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ETH_OPTIMISM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("ETH_OPTIMISM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("ETH_OPTIMISM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ETH_BASE", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("ETH_BASE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("ETH_BASE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_XPL_PLASMA", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("XPL_PLASMA")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("XPL_PLASMA"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_BNB_BSC", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("BNB_BSC")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("BNB_BSC"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_POL_POLYGON", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("POL_POLYGON")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("POL_POLYGON"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TESTCOIN_ETHEREUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("TESTCOIN_ETHEREUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("TESTCOIN_ETHEREUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TESTCOIN_OPTIMISM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("TESTCOIN_OPTIMISM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("TESTCOIN_OPTIMISM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TESTCOIN_PLASMA", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("TESTCOIN_PLASMA")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("TESTCOIN_PLASMA"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TESTSTABLECOIN_ETHEREUM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("TESTSTABLECOIN_ETHEREUM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("TESTSTABLECOIN_ETHEREUM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TESTSTABLECOIN_OPTIMISM", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("TESTSTABLECOIN_OPTIMISM")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("TESTSTABLECOIN_OPTIMISM"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TESTSTABLECOIN_PLASMA", func(t *testing.T) {
		t.Parallel()
		val, err := NewCryptopayAssetIDFromString("TESTSTABLECOIN_PLASMA")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CryptopayAssetID("TESTSTABLECOIN_PLASMA"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCryptopayAssetIDFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCryptopayAssetIDFromString("USDT_ETHEREUM")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumWebhookPaymentEventType(t *testing.T) {
	t.Run("NewFromString_payment_accepted", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookPaymentEventTypeFromString("payment.accepted")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookPaymentEventType("payment.accepted"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_payment_success", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookPaymentEventTypeFromString("payment.success")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookPaymentEventType("payment.success"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_payment_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookPaymentEventTypeFromString("payment.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookPaymentEventType("payment.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewWebhookPaymentEventTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewWebhookPaymentEventTypeFromString("payment.accepted")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumWebhookStaticDepositEventType(t *testing.T) {
	t.Run("NewFromString_static_deposit_accepted", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookStaticDepositEventTypeFromString("static_deposit.accepted")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookStaticDepositEventType("static_deposit.accepted"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_static_deposit_success", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookStaticDepositEventTypeFromString("static_deposit.success")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookStaticDepositEventType("static_deposit.success"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewWebhookStaticDepositEventTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewWebhookStaticDepositEventTypeFromString("static_deposit.accepted")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesControllerErrorResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ControllerErrorResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ControllerErrorResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookPaymentEvent(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookPaymentEvent{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookPaymentEvent
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookStaticDepositEvent(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookStaticDepositEvent{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookStaticDepositEvent
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
