// Code generated by Fern. DO NOT EDIT.

package payments

import (
	context "context"

	suwardsdkgo "github.com/crylabsorg/suward-sdk-go"
	core "github.com/crylabsorg/suward-sdk-go/core"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	option "github.com/crylabsorg/suward-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List payments for a project
func (c *Client) ListPayments(
	ctx context.Context,
	request *suwardsdkgo.GetV1PaymentsRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayListPaymentsResponse, error) {
	response, err := c.WithRawResponse.ListPayments(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new payment
func (c *Client) CreatePayment(
	ctx context.Context,
	request *suwardsdkgo.CryptopayCreatePaymentRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayPaymentResponse, error) {
	response, err := c.WithRawResponse.CreatePayment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns full payment details when called with an API key (merchant view).
// Returns limited payment details when called without an API key (customer view).
func (c *Client) GetPayment(
	ctx context.Context,
	request *suwardsdkgo.GetV1PaymentsPaymentIDRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.GetV1PaymentsPaymentIDResponse, error) {
	response, err := c.WithRawResponse.GetPayment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Activate a payment (public, customer-facing)
func (c *Client) ActivatePayment(
	ctx context.Context,
	request *suwardsdkgo.PostV1PaymentsPaymentIDActivateRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayPublicPaymentResponse, error) {
	response, err := c.WithRawResponse.ActivatePayment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cancel a payment
func (c *Client) CancelPayment(
	ctx context.Context,
	request *suwardsdkgo.PostV1PaymentsPaymentIDCancelRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayPaymentResponse, error) {
	response, err := c.WithRawResponse.CancelPayment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Simulate payment status change (test mode only)
func (c *Client) SimulatePayment(
	ctx context.Context,
	request *suwardsdkgo.CryptopaySimulatePaymentRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayPaymentResponse, error) {
	response, err := c.WithRawResponse.SimulatePayment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the platform fee, estimated network fee, and net amount for a payment of `amount` in `asset`, without creating anything. All monetary fields are integer strings in the asset's smallest unit.
func (c *Client) QuotePaymentFees(
	ctx context.Context,
	request *suwardsdkgo.CryptopayQuotePaymentRequest,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayQuotePaymentResponse, error) {
	response, err := c.WithRawResponse.QuotePaymentFees(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
