// Code generated by Fern. DO NOT EDIT.

package assets

import (
	context "context"

	suwardsdkgo "github.com/crylabsorg/suward-sdk-go"
	core "github.com/crylabsorg/suward-sdk-go/core"
	internal "github.com/crylabsorg/suward-sdk-go/internal"
	option "github.com/crylabsorg/suward-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns all assets accepted by the Suward gateway. No authentication required.
func (c *Client) ListAcceptedAssets(
	ctx context.Context,
	opts ...option.RequestOption,
) (*suwardsdkgo.GetV1AssetsResponse, error) {
	response, err := c.WithRawResponse.ListAcceptedAssets(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns all supported blockchains (informational). No authentication required.
func (c *Client) ListSupportedBlockchains(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*suwardsdkgo.CryptopayBlockchainResponse, error) {
	response, err := c.WithRawResponse.ListSupportedBlockchains(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the asset groups (same-symbol assets pooled across chains, e.g. USDT, USDC, ETH). No authentication required.
func (c *Client) ListAssetGroups(
	ctx context.Context,
	opts ...option.RequestOption,
) (*suwardsdkgo.GetV1AssetGroupsResponse, error) {
	response, err := c.WithRawResponse.ListAssetGroups(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the current USD price for every asset group, served from cache and refreshed in the background. No authentication required.
func (c *Client) ListAssetPrices(
	ctx context.Context,
	opts ...option.RequestOption,
) (*suwardsdkgo.GetV1PricesResponse, error) {
	response, err := c.WithRawResponse.ListAssetPrices(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the asset/network pairs available for withdrawal and the flat withdrawal fee (USD). No authentication required.
func (c *Client) GetWithdrawalConfiguration(
	ctx context.Context,
	opts ...option.RequestOption,
) (*suwardsdkgo.CryptopayWithdrawalConfigResponse, error) {
	response, err := c.WithRawResponse.GetWithdrawalConfiguration(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
