// Code generated by Fern. DO NOT EDIT.

package static_wallets_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	suwardsdkgo "github.com/crylabsorg/suward-sdk-go"
	client "github.com/crylabsorg/suward-sdk-go/client"
	option "github.com/crylabsorg/suward-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestStaticWalletsListStaticWalletsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.GetV1StaticWalletsRequest{}
	_, invocationErr := client.StaticWallets.ListStaticWallets(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsListStaticWalletsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsListStaticWalletsWithWireMock", "GET", "/v1/static-wallets", nil, 1)
}

func TestStaticWalletsCreateStaticWalletWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.CryptopayCreateStaticWalletRequest{}
	_, invocationErr := client.StaticWallets.CreateStaticWallet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsCreateStaticWalletWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsCreateStaticWalletWithWireMock", "POST", "/v1/static-wallets", nil, 1)
}

func TestStaticWalletsGetStaticWalletWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.GetV1StaticWalletsStaticWalletIDRequest{
		StaticWalletID: "staticWalletId",
	}
	_, invocationErr := client.StaticWallets.GetStaticWallet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsGetStaticWalletWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsGetStaticWalletWithWireMock", "GET", "/v1/static-wallets/staticWalletId", nil, 1)
}

func TestStaticWalletsDeleteStaticWalletWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.DeleteV1StaticWalletsStaticWalletIDRequest{
		StaticWalletID: "staticWalletId",
	}
	_, invocationErr := client.StaticWallets.DeleteStaticWallet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsDeleteStaticWalletWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsDeleteStaticWalletWithWireMock", "DELETE", "/v1/static-wallets/staticWalletId", nil, 1)
}

func TestStaticWalletsUpdateStaticWalletWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.CryptopayUpdateStaticWalletRequest{
		StaticWalletID: "staticWalletId",
	}
	_, invocationErr := client.StaticWallets.UpdateStaticWallet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsUpdateStaticWalletWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsUpdateStaticWalletWithWireMock", "PATCH", "/v1/static-wallets/staticWalletId", nil, 1)
}

func TestStaticWalletsListStaticWalletDepositsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.GetV1StaticWalletsStaticWalletIDDepositsRequest{
		StaticWalletID: "staticWalletId",
	}
	_, invocationErr := client.StaticWallets.ListStaticWalletDeposits(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsListStaticWalletDepositsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsListStaticWalletDepositsWithWireMock", "GET", "/v1/static-wallets/staticWalletId/deposits", nil, 1)
}

func TestStaticWalletsGetStaticWalletDepositWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.GetV1StaticWalletsStaticWalletIDDepositsDepositIDRequest{
		StaticWalletID: "staticWalletId",
		DepositID:      "depositId",
	}
	_, invocationErr := client.StaticWallets.GetStaticWalletDeposit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsGetStaticWalletDepositWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsGetStaticWalletDepositWithWireMock", "GET", "/v1/static-wallets/staticWalletId/deposits/depositId", nil, 1)
}

func TestStaticWalletsSimulateStaticWalletDepositWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &suwardsdkgo.CryptopaySimulateStaticDepositRequest{
		StaticWalletID: "staticWalletId",
		Amount:         "amount",
		Asset:          suwardsdkgo.CryptopayAssetIDUsdtEthereum,
		Status:         suwardsdkgo.CryptopaySimulateStaticDepositRequestStatusDetected,
	}
	_, invocationErr := client.StaticWallets.SimulateStaticWalletDeposit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStaticWalletsSimulateStaticWalletDepositWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStaticWalletsSimulateStaticWalletDepositWithWireMock", "POST", "/v1/static-wallets/staticWalletId/simulate", nil, 1)
}
